### ISSUE TITLE
Suggest quake terminal

### ISSUE THREAD

**Issue by a-wing** [martyr-deepin/deepin-terminal-gtk#1]
Suggest "hide quake windows after lost focus" , again use Shortcut key terminal able hide

**Comment by ceyhunn** [comment]
Hi, @a-wing  

Use latest version of deepin-terminal, there must be option like your suggestion...

**Comment by a-wing** [comment]
@ceyhunnabiyev NO,NO,v2.3.3-1 don't have this , I'm talking about optioned "hide quake windows after lost focus"  after . if your Shortcut key strat deepin-quake . deepin-quake have appear . but  your again Shortcut key start deepin-quake don't disappear . I suggest again  Shortcut key start deepin-quake disappear . look like guake & yakuake all exist this function. Think

**Comment by manateelazycat** [comment]
@a-wing 
When you set 'hide_quakewindow_after_lost_focus' with true, deepin-terminal will hide after you click someplace out of deepin-terminal area.

Can you binding any keystroke to command 'deepin-terminal --quake-mode', when you first press keystroke, quake terminal will show, when you press keystroke agian, quake window will hide.

**Comment by tsouhaieb** [comment]
please add a shortcut to show/hide quake-mode in deepin terminal

**Comment by souhaiebtar** [comment]
@manateelazycat even without setting 'hide_quakewindow_after_lost_focus' with true, after you bind 'deepin-terminal --quake-mode' to a keystroke (in my case Super+T, super for windows button), typing Super+T drop down deepin-terminal from above, typing it again make it disepear, i'm using deepin terminal 2.1
