### ISSUE TITLE
Encoding visual feedback isn't reset to UTF-8

### ISSUE THREAD

**Issue by egmontkob** [martyr-deepin/deepin-terminal-gtk#105]
With UTF-8 as default, invoke Right-click -> Encoding. Switch to something else (e.g. ISO-8859-1).

Optionally dismiss the sidebar (by clicking over the terminal), confirm the change in the behavior, and re-open the Encoding sidebar.

Change back to UTF-8. Dismiss the sidebar (by clicking over the terminal). Confirm that the behavior is UTF-8.

Open the Encoding sidebar again. Notice that the latest non-UTF-8 choice (e.g. ISO-8859-1) is selected, instead of UTF-8 as expected.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
