### ISSUE TITLE
extra characters after close-brace

### ISSUE THREAD

**Issue by felocru** [martyr-deepin/deepin-terminal-gtk#109]
In remote administration. When entering the password, the password contains characters that bring conflicts.
```
extra characters after close-brace
    while executing
"set password {dV82}g"
    (file "/tmp/deepin-terminal-5B9AVZ" line 36)
```

**Comment by BLumia** [comment]
Could you provide a sample password string which can reproduce this issue? Thx.

**Comment by felocru** [comment]
Thanks version 3.2.7 solves the problem.
