### ISSUE TITLE
Crash when open setting

### ISSUE THREAD

**Issue by uisyudha** [martyr-deepin/deepin-terminal-gtk#11]
afte update it suddenly close when open setting menu.

from dmesg: 
deepin-terminal[848]: segfault at 29 ip 00007fd75361da14 sp 00007ffda79332d8 error 4 in libc-2.25.so[7fd7535a1000+19b000]

**Comment by manateelazycat** [comment]
@felixonmars has test yesterday:
vala 0.36.3 failed
vala 0.34.6 ok
vala 0.36.0 failed

It's seen a bug of vala that cause by commits:
https://github.com/GNOME/vala/commit/e2422670e9438153faa697c5aedc7653289f7354
https://github.com/GNOME/vala/commit/971f474f105bd1bbee7144eb4183635084c96821

I will figure out how to make deepin-terminal works with newer vala.

**Comment by manateelazycat** [comment]
this bug duplicate with https://github.com/linuxdeepin/deepin-terminal/issues/10

close this one.
