### ISSUE TITLE
为什么在系统dark主题下终端设置还是亮色？能不能跟随系统进行变化？

### ISSUE THREAD

**Issue by iceqing** [martyr-deepin/deepin-terminal-gtk#110]
![deepinscreenshot_select-area_20190112140115](https://user-images.githubusercontent.com/39587710/51069877-aa414d80-1672-11e9-874f-c9f7fd05a48c.png)

**Comment by BLumia** [comment]
主题功能是在逐渐完善支持的，现在并非所有的深度自家应用都具备完整的亮色和暗色主题支持，主题相关的支持会逐步跟进，包括现在分应用设置亮色暗色主题将会逐渐改为跟随系统主题，等等。

另外值得一提的是，深度自家应用当前只有深度终端不是 Qt 项目，故如果我们调整主题样式，相当于还是要做两次工作，即 Qt 程序适配和 GTK 适配，以达到视觉效果符合设计给出的规范。

由于项目安排，此类功能优先级不会特别高，但已经在计划内。如果您有兴趣帮助我们完善此类功能，欢迎提交 Patch ;)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
