### ISSUE TITLE
是否可以关闭Ctrl+触控板滑动改变透明度

### ISSUE THREAD

**Issue by PikachuHy** [martyr-deepin/deepin-terminal-gtk#111]
我的使用场景是，触控板手指上下滑动看日志，如果出现异常，需要按Ctrl+C终止进程，
但是一般这个时候会误触发改变透明度的一个操作，
请问是否可以关闭这个操作？谢谢

**Comment by BLumia** [comment]
@wangjia12

**Comment by wangjia12** [comment]
目前收到的这种误触反馈很少，我们会持续关注这类问题，如果有必要会进行修改。

**Comment by i-mine** [comment]
还是挺频繁的，查看大量日志信息或者vim操作的时候，确实很容易触发变透明，建议能够添加禁用

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
