### ISSUE TITLE
建议文件上传或下载支持文件夹和多个文件

### ISSUE THREAD

**Issue by jay763190097** [martyr-deepin/deepin-terminal-gtk#120]
现在可以通过右键文件上传或者下载进行文件传输，但是单个文件太耗时，特别是多文件的时候。当然可以先压缩再上传，可是这确实是一个必备的功能。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
