### ISSUE TITLE
Tab title is always blank when using zsh

### ISSUE THREAD

**Issue by howyay** [martyr-deepin/deepin-terminal-gtk#121]
The tab title does not show and does not change according to my current directory when using zsh, but it works with bash, haven't tried fish but I soon will.

**Comment by howyay** [comment]
It does work with fish default configuration.

**Comment by BLumia** [comment]
Please check your zsh configuration, mine zsh (oh_my_zsh with my own configuration) works fine.

btw, did gnome-terminal has the same problem in your case?

fyi:

https://github.com/linuxdeepin/deepin-terminal/blob/3.2.1/widget/terminal.vala#L744-L789

**Comment by BLumia** [comment]
Closing due to not a bug and no response. Feel free to open an new issue and link back to this issue if you still have this problem, and don't forget to provide more details so others can help you out.
