### ISSUE TITLE
Can not set cursor style

### ISSUE THREAD

**Issue by fksad** [martyr-deepin/deepin-terminal-gtk#122]
env:
deeping 15.9.1
terminal 3.2.1
zsh 5.5.1

issue:
Style of cursor remains block no matter what set in settings.

**Comment by egmontkob** [comment]
It's possible for some escape sequences to override the setting, see e.g. https://superuser.com/a/911665/278816. Perhaps you (or your zsh configuration) emits one of these.

**Comment by fksad** [comment]
Everything became normal after reboot
