### ISSUE TITLE
Unable to find font.

### ISSUE THREAD

**Issue by cloudhan** [martyr-deepin/deepin-terminal-gtk#123]
Monospaced [Sarasa-Gothic](https://github.com/be5invis/Sarasa-Gothic) can not be find through the font drop down menu. 

It seems deepin-terminal is base on spacing to determine if a font is monospaced or not. But Sarasa-Gothic spacing is 90, IIRC. Maybe it needs a more robust mechanism to find monospace fonts?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
