### ISSUE TITLE
Problem with material color theme

### ISSUE THREAD

**Issue by ghost** [martyr-deepin/deepin-terminal-gtk#126]
I opened with nano program python file and don't see any operator like try, import. Screenshot is below
I tried to change similar color in material file by path /usr/share/deepin-terminal/theme but no luck. Can you please provide a way how to change it please?
![screenshot from 2019-02-28 20-20-00](https://user-images.githubusercontent.com/6771075/53589170-bee49100-3b9f-11e9-9f8d-c6f12c7f61e9.png)

**Comment by avently** [comment]
You can copy theme you like to ~/.config/deepin/deepin-terminal/themes/ and then edit it as you like. 
For example, if you like a theme named breeze:
$ cp /usr/share/deepin-terminal/theme/breeze ~/.config/deepin/deepin-terminal/themes/my-breeze
$ nano ~/.config/deepin/deepin-terminal/themes/my-breeze

Edit it and than choose this theme (my-breeze) inside the terminal theme chooser. That's it.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
