### ISSUE TITLE
Double window border under kwin5

### ISSUE THREAD

**Issue by farseerfc** [martyr-deepin/deepin-terminal-gtk#127]
When using deepin-terminal under kde5 kwin, terminal windows have double window borders, which looks ugly. Should at least instruct kwin to stop using window decoration as deepin-movie does.
![image](https://user-images.githubusercontent.com/861563/54074860-3ec6d580-42db-11e9-8ec8-3e05475eebda.png)

**Comment by BLumia** [comment]
Please consider turn off the "**Enforces Window Decorations on GTK+ window**" option under "**Window Management > KWin Scripts**" in KDE's `systemsettings5` ?

Unlike other deepin apps, deepin-terminal is a GTK/vala application, so the behavior may not same under other wm :)

@zccrs is there any way to tell kwin to disable window decoration for GTK app?

**Comment by farseerfc** [comment]
It's hard to instruct kwin to disable decoration for ALL gtk3 windows, but it can be done for your own window.

Consider applying "_KDE_NET_WM_WINDOW_TYPE_OVERRIDE" to "_NET_WM_WINDOW_TYPE", this will instruct kwin to NOT apply decorations on the specific window. I see deepin-movie has this property (possibly set by Qt)

https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html
https://techbase.kde.org/Projects/KWin/Window_Decoration_Policy#Windows_With_Decorations

**Comment by BLumia** [comment]
Sorry for the late reply. After discussing with @zccrs , we think this sort of wm specific hack shouldn't be done from the application side (should be done inside GTK itself), thus all GTK application will no longer have issue with window decoration.

**Comment by farseerfc** [comment]
The appearance of gtk3 (with GtkHeaderBar) applications is OK under kwin5, with or without system decoration. OK means that they will render shadows and borders correctly when using system decoration, and hide shadows and borders when system decoration is disabled (although no shadow is applied in this case). 
This behavior of double window border/shadow is only present on deepin-terminal.
![image](https://user-images.githubusercontent.com/861563/54508493-6f68d800-4989-11e9-86ff-0f1d0bdd5e8e.png)

**Comment by avently** [comment]
@farseerfc for WMs like i3 I made a hack that disables these borders. 
This line
https://github.com/linuxdeepin/deepin-terminal/blob/master/lib/utils.vala#L116
have a list of binaries running that will have zero borders. So you can type in that line your kwin binary name (maybe it's called "kwin") and try to build and run the terminal. If it will work correctly we can then include kwin as an exception into the master branch.

**Comment by farseerfc** [comment]
kwin as of 5.17.4 has support for GTK3 style Client Side Decoration, thus this bug is fixed by upstream. Closing the bug.
