### ISSUE TITLE
Change the quake terminal position

### ISSUE THREAD

**Issue by godardt** [martyr-deepin/deepin-terminal-gtk#129]
Afaik the `~/.config/deepin/deepin-terminal/config.conf` doesn't allow me to change where the quake terminal will pop up when I hit the keyboard shortcut. It's always popping up from the top of the screen, I would like to have it vertically aligned, coming up from the left side instead but I can't find any option for that. Also sometimes it seems hitting the keyboard shortcut doesn't always give the terminal the focus right away, happens 1/2 times.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
