### ISSUE TITLE
终端分屏后两个屏幕中间的线颜色怎么修改

### ISSUE THREAD

**Issue by zhaoyunxing92** [martyr-deepin/deepin-terminal-gtk#133]
我屏幕分屏了但是两个屏中间的先不明显，很男分清楚那个是那个，我想知道是在`/usr/share/deepin-terminal` 目录下修改什么那里就可以达到效果吗

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
