### ISSUE TITLE
getting below errors in Ubuntu 17.10

### ISSUE THREAD

**Issue by ghost** [martyr-deepin/deepin-terminal-gtk#14]
Iam trying to build deepin terminal in Ubuntu 17.10. 
On executing "make", i am getting the below errors.

[ 19%] Generating lib/animation.c, lib/config.c, lib/constant.c, lib/draw.c, lib/keymap.c, lib/menu.c, lib/utils.c, lib/xutils.c, widget/about_dialog.c, widget/about_widget.c, widget/add_button.c, widget/appbar.c, widget/check_button.c, widget/click_event_box.c, widget/command_button.c, widget/command_dialog.c, widget/command_panel.c, widget/base_panel.c, widget/config_window.c, widget/confirm_dialog.c, widget/cursor_toggle_button.c, widget/dialog.c, widget/dialog_button.c, widget/encoding_button.c, widget/encoding_panel.c, widget/entry.c, widget/entry_menu.c, widget/file_button.c, widget/image_button.c, widget/window_button.c, widget/panel_button.c, widget/password_button.c, widget/preference.c, widget/preference_slidebar.c, widget/progressbar.c, widget/quake_window.c, widget/remote_panel.c, widget/remote_server_dialog.c, widget/link_button.c, widget/search_entry.c, widget/search_panel.c, widget/server_button.c, widget/server_group_button.c, widget/shortcut_entry.c, widget/split_line.c, widget/spinbutton.c, widget/switcher.c, widget/tabbar.c, widget/terminal.c, widget/text_button.c, widget/theme_button.c, widget/theme_panel.c, widget/titlebar.c, widget/window.c, widget/window_event_area.c, widget/workspace.c, widget/workspace_manager.c, main.c
gee-0.8.vapi:278.3-278.31: error: overriding method `Gee.HashSet.foreach' is incompatible with base method `Gee.AbstractCollection.foreach': incompatible type of parameter 1.
		public override bool @foreach (Gee.ForallFunc f);
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gee-0.8.vapi:278.3-278.31: error: Gee.HashSet.foreach: no suitable method found to override
		public override bool @foreach (Gee.ForallFunc f);
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gee-0.8.vapi:368.3-368.31: error: overriding method `Gee.PriorityQueue.foreach' is incompatible with base method `Gee.AbstractCollection.foreach': incompatible type of parameter 1.
		public override bool @foreach (Gee.ForallFunc f);
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gee-0.8.vapi:368.3-368.31: error: Gee.PriorityQueue.foreach: no suitable method found to override
		public override bool @foreach (Gee.ForallFunc f);
		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/opt/deepin-terminal/./lib/utils.vala:413.22-413.45: warning: Gdk.Screen.get_active_window has been deprecated since 3.22
/opt/deepin-terminal/./lib/utils.vala:415.20-415.47: warning: Gdk.Screen.get_monitor_at_window has been deprecated since 3.22
/opt/deepin-terminal/./lib/utils.vala:417.20-417.45: warning: Gdk.Screen.get_primary_monitor has been deprecated since 3.22
/opt/deepin-terminal/./lib/utils.vala:425.16-425.42: warning: Gdk.Screen.get_monitor_at_point has been deprecated since 3.22
/opt/deepin-terminal/./widget/quake_window.vala:47.13-47.39: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
/opt/deepin-terminal/./widget/quake_window.vala:374.21-374.47: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
/opt/deepin-terminal/./widget/quake_window.vala:213.34-213.61: warning: Gdk.Screen.get_monitor_at_window has been deprecated since 3.22
/opt/deepin-terminal/./widget/quake_window.vala:216.13-216.39: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
/opt/deepin-terminal/./widget/window.vala:59.13-59.39: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
/opt/deepin-terminal/./widget/config_window.vala:524.29-524.55: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
Compilation failed: 4 error(s), 10 warning(s)
CMakeFiles/deepin-terminal.dir/build.make:118: recipe for target 'lib/animation.c' failed
make[2]: *** [lib/animation.c] Error 1
CMakeFiles/Makefile2:844: recipe for target 'CMakeFiles/deepin-terminal.dir/all' failed
make[1]: *** [CMakeFiles/deepin-terminal.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by manateelazycat** [comment]
Has fixed by patch https://github.com/manateelazycat/deepin-terminal/commit/0b0462d785243043e149abf29fb98d8449f74536
