### ISSUE TITLE
Custom command title is invisible

### ISSUE THREAD

**Issue by phkorn** [martyr-deepin/deepin-terminal-gtk#143]
If I add a custom command with a & in the title (like build & deploy), the title won't be displayed anymore in the custom commands overview.

![title_bug](https://user-images.githubusercontent.com/1607865/56025197-ec316c80-5d11-11e9-83f6-6a0b0be5be23.png)

**Comment by BLumia** [comment]
Should be resolved in https://github.com/linuxdeepin/deepin-terminal/pull/188 and thanks again for @timothyvanderaerden 's contribution! :heart:
