### ISSUE TITLE
是否支持45度窗口拉伸

### ISSUE THREAD

**Issue by Quanyu-Mars** [martyr-deepin/deepin-terminal-gtk#144]
这个功能感觉还是很重要，可以和其他窗口操作习惯统一。

我当前平台相关情况:
deepin-terminal version: 3.2.1.1
OS：fedora/deepin-desktop

**Comment by BLumia** [comment]
没听懂需求，是指拖拽右下角窗口边缘调整大小吗？如果是的话，一直都是支持的才对。

不过在没开窗管混成的时候边框的确有些窄，不太容易拖动边缘，这个是已知问题。

**Comment by FlyMan2004** [comment]
他可能想要四个角都可以调整大小？

**Comment by BLumia** [comment]
四个角的确都可以才对。以及换 kwin 后这个问题应该也不会出现在 2d 窗管模式（就是不开混成的 kwin）下了。不清楚 fedora 那边有没有把 dde-kwin port 过去。

所以还是想确认一下细节。

**Comment by cheese** [comment]
> 四个角的确都可以才对。以及换 kwin 后这个问题应该也不会出现在 2d 窗管模式（就是不开混成的 kwin）下了。不清楚 fedora 那边有没有把 dde-kwin port 过去。
> 
> dde-所以还是想确认一下细节。

dde-kwin 也已经加到 Fedora 了（在 Fedora 里叫 deepin-kwin），只是没有默认安装。
刚试了下 terminal 在 dde-kwin 下的确没有边缘问题
