### ISSUE TITLE
Archlinux下全屏问题

### ISSUE THREAD

**Issue by VWWVVW** [martyr-deepin/deepin-terminal-gtk#15]
桌面环境xfce
全屏后恢复（双击F11）后顶端标题栏显示出错，改变大小后恢复

**Comment by manateelazycat** [comment]
标题栏出错截图能否给我看一下？

**Comment by manateelazycat** [comment]
我测试了所有窗口管理器都没有问题，我发现在XFCE里面，当窗口分屏或者全屏时，窗口的状态不是 Gdk.WindowState.TILED 或 Gdk.WindowState.FULLSCREEN，而是一个非常错误的窗口状态 GDK_WINDOW_STATE_FOCUSED

这样导致深度终端无法正确的处理窗口状态，因为 XFCE 里面，正常窗口和全屏窗口都是 GDK_WINDOW_STATE_FOCUSED 窗口状态。

别的程序之所有没有问题，都是因为他们都是用窗口管理器绘制的边框，XFCE的窗口管理器虽然处理全屏状态有问题，但是窗口管理器自己内部处理了。
像深度终端这种自己控制边框器的程序，XFCE就是错误的处理。

我也研究了别的终端的源码实现，发现都是 hacking way： https://github.com/jana-choi/OpenSource/blob/383a49375fa816fe3f2504d67e8f7460253c407f/mypaint-mypaint/gui/workspace.py

所以，我认为这应该是XFCE自己窗口管理器代码处理不规范的问题，深度终端不会为了一个不按窗口管理器标准协议实现的窗口管理器而添加 hacking code. 抱歉。
