### ISSUE TITLE
Terminal Blur Does not work after fresh install of Deepin 15.10

### ISSUE THREAD

**Issue by RocketLR** [martyr-deepin/deepin-terminal-gtk#151]
I just did a fresh install of Deepin 15.10 on two seperate machines. 
And on both of them the blur does not take effect after i turn it on in the settings menu.
Any suggestions how to fix this?

![DeepinScreenshot_20190502134836](https://user-images.githubusercontent.com/25768033/57073317-02af6000-6ce1-11e9-8593-940d77f0b0cf.png)

**Comment by BLumia** [comment]
Seems it's not working under KWin, will looking into this issue later, patches are welcome :)

https://github.com/linuxdeepin/developer-center/issues/1133

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/deepin-terminal/blob/b1628ce1c408c100cd533614008620ff195c3e85/widget/window.vala#L330-L370

KWin (and also dde-kwin) does not support `_NET_WM_DEEPIN_BLUR_REGION_ROUNDED`. Not familiar with WM properties, did `_KDE_NET_WM_BLUR_BEHIND_REGION` works? @zccrs
