### ISSUE TITLE
Active tab bottom border is over the terminal

### ISSUE THREAD

**Issue by fedenator** [martyr-deepin/deepin-terminal-gtk#158]
Current behavior:
![deepin-tab](https://user-images.githubusercontent.com/8305900/57572047-1e56ec80-73ec-11e9-9215-1f46d2a96dac.png)

Expected behavior:
The bottom border that indicates which tab is active should be over the tab
![deepin-tab-fixed](https://user-images.githubusercontent.com/8305900/57572137-cec4f080-73ec-11e9-8ca2-e95e9a449386.png)

It's a minor thing but is kinnda annoying

**Comment by BLumia** [comment]
Thanks to @timothyvanderaerden and this issue should be resolved in https://github.com/linuxdeepin/deepin-terminal/pull/184 :)
