### ISSUE TITLE
Missing dependency to deepin-menu

### ISSUE THREAD

**Issue by hosiet** [martyr-deepin/deepin-terminal-gtk#16]
Without deepin-menu, deepin-terminal won't work properly. E.g., right click won't pop up any menu.

**Comment by rabitdash** [comment]
http://www.nekomiao.me/2016/08/10/ubuntu-1604-install-deepin-terminal/
添加软件源，deepin-menu可以从软件源中安装

**Comment by hosiet** [comment]
@rabitdash 不是装不装的问题，装是必须装的。

问题是这个包名没有写进 debian/control 文件。

**Comment by hosiet** [comment]
18f01ca7a1963efe28e302e3bb24b2556d1b7e89 这个提交解决了问题。
