### ISSUE TITLE
How to import/export servers `remote management`?

### ISSUE THREAD

**Issue by Honghe** [martyr-deepin/deepin-terminal-gtk#163]
Environment:
- Ubuntu 18.04.2

**Comment by BLumia** [comment]
Consider manually backup the config file at `~/.config/deepin/deepin-terminal/server-config.conf`?

https://github.com/linuxdeepin/deepin-terminal#config-file

**Comment by strive1216** [comment]
Which does not contain a password

**Comment by BLumia** [comment]
> Which does not contain a password

Passwords stored in the GNOME keyring so you should [backup GNOME keyring](https://askubuntu.com/questions/907425/how-do-i-back-up-and-restore-passwords-and-keys) if you want to backup these passwords. You can also see these passwords via `seahorse` if you like.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
