### ISSUE TITLE
[Feature Request]  Does deepin-terminal have command line for tab?

### ISSUE THREAD

**Issue by gusbemacbe** [martyr-deepin/deepin-terminal-gtk#167]
Hello!

For example:

```bash
deepin-terminal -w --tab %f
```

I want to use it for `~/.local/share/kservices5/ServiceMenus/konsolehere.desktop`, so I will not have to open many windows instead of many tabs in one window.

**Comment by BLumia** [comment]
Seems not, but good idea.

**Comment by BLumia** [comment]
Should be resolved in https://github.com/linuxdeepin/deepin-terminal/pull/189 :)

**Comment by gusbemacbe** [comment]
Great!
