### ISSUE TITLE
terminal window constantly grows to fullscreen

### ISSUE THREAD

**Issue by BlackIkeEagle** [martyr-deepin/deepin-terminal-gtk#168]
Since 3.2.5 the terminal window always grows to maximized

3.2.4 does not have this behaviour

![deepin-screen-recorder_Select area_20190601113350](https://user-images.githubusercontent.com/293691/58746682-3a850100-8461-11e9-911a-424daaca662b.gif)

**Comment by chintensakai** [comment]
the same as you，and I'm using archlinux with deepin.

**Comment by ForeverZer0** [comment]
Same. I use Arch, btw.

It randomly grows under various conditions, such as right-clicking anywhere within the terminal window, left-clicking the title bar. It will also just keep growing beyond the window for as long as you click. 

In addition, it does not remember that previous size when closing.

### Reproduce
* Open a terminal (notice how it goes fullscreen)
* Resize to dimensions people actually use
* Click around on the window, watch it grow
* Resize to dimensions people actually use (again)
* Close terminal
* Open terminal (notice it is full-screen again)

Needless to say, this is an absolutely **CRITICAL** bug, making using the terminal so annoying that it is unusable.

To any Arch newcomers experiencing this issue, and like me unfortunately already deleted it from the cache, you can download the previous version from from the community repo [here](https://archive.archlinux.org/repos/2019/05/31/community/os/x86_64/deepin-terminal-3.2.4-1-x86_64.pkg.tar.xz), uninstall the old terminal, then `pacman -U deepin-terminal-3.2.4-1-x86_64.pkg.tar.xz`. 

You will have to make sure not to update it until it gets fixed.

**Comment by BLumia** [comment]
Not sure, cannot reproduce it under Deepin with DDE and Mate, would like to test it under Arch with KDE later.

btw, did anyone tested if revert https://github.com/linuxdeepin/deepin-terminal/commit/b757ef93f96d0a40060a9db9bde33188c0f7186f can solve this issue?

**Comment by ForeverZer0** [comment]
So far, looks like Deepin on Arch since that is the setup @BlackIkeEagle, @toyranger , and myself all are using. Not sure if KDE users having any issues, hopefully your tests will help figure that out.

I am using proprietary NVIDIA drivers, with libinput if that helps.

**Comment by chirs241097** [comment]
Can't reproduce this issue using my Gentoo test environment. I'm using KWin 5.15.5 (with KDE though) and latest git sources of deepin projects.
I'm suspecting that this could be the result of a bad interaction between a newer version of KWin and the KWin plugin for DDE as `dde-kwin` is developed against an older verion of KWin (5.8.6). I'll have a look into that later.

**Comment by BlackIkeEagle** [comment]
I don't have kwin installed.

List of deepin packages:
deepin-account-faces
deepin-anything
deepin-anything-module-bede
deepin-anything-module-bede-lts
deepin-api
deepin-clutter
deepin-cogl
deepin-control-center
deepin-daemon
deepin-desktop-base
deepin-desktop-schemas
deepin-dock
deepin-file-manager
deepin-gtk-theme
deepin-icon-theme
deepin-image-viewer
deepin-launcher
deepin-manual
deepin-menu
deepin-metacity
deepin-movie
deepin-mutter
deepin-network-utils
deepin-polkit-agent
deepin-polkit-agent-ext-gnomekeyring
deepin-qt-dbus-factory
deepin-qt5dxcb-plugin
deepin-qt5integration
deepin-screen-recorder
deepin-screensaver
deepin-screenshot
deepin-session-ui
deepin-shortcut-viewer
deepin-sound-theme
deepin-system-monitor
deepin-terminal
deepin-turbo
deepin-wallpapers
deepin-wm
dtkwidget
dtkwm
startdde

the kwin dependency is not mandatory it seems, do we require to use deepin-kwin instead of deepin-wm already?

**Comment by chirs241097** [comment]
> do we require to use deepin-kwin instead of deepin-wm already?

Sooner or later, as `deepin-wm` is no longer actively maintained now.

I've confirmed this bug is reproducible with `deepin-wm` or `deepin-metacity` and will put up a commit to resolve the issue soon. For now you can either downgrade `deepin-terminal` or try installing `deepin-kwin` as a workaround.

**Comment by keybreak** [comment]
I confirmed this bug also for deepin-kwin on Arch, so no it's not the cause.

**Comment by chirs241097** [comment]
> I confirmed this bug also for deepin-kwin on Arch, so no it's not the cause.

Couldn't reproduce the bug with a fresh install of Arch + deepin + deepin-kwin here (in VirtualBox though). Neither could I reproduce it on one of our development machines that is running Arch. Mind giving more details on that?

**Comment by keybreak** [comment]
@chirs241097 
Not sure if i can - it's just fresh Arch Deepin with **deepin-kwin** installed on VirtualBox VM 2 days ago...

If you can ask more specific questions i will provide more info

**Comment by BLumia** [comment]
Simply revert the affacted commit is okay, after dde-kwin can draw the application shadow on kwin's side, we can remove the self drawed deepin-terminal shadow so the original problem will no longer exist on whatever wm what user are using.

**Comment by BLumia** [comment]
Should be resolved in 3.2.5.1 as a hot fix.
