### ISSUE TITLE
blur option not working

### ISSUE THREAD

**Issue by I-Love-My-Ex** [martyr-deepin/deepin-terminal-gtk#171]
on both fresh install of arch and mint the blur option is not working and i dont see any extra file to install to fix this problem

**Comment by I-Love-My-Ex** [comment]
is that option like part of the deepin wm?
if so why not make an extra pack to fix that for thoes who dont use dde but use deepin tools

**Comment by BLumia** [comment]
The blur effect requires wm support to work, if you are using a wm which support `_NET_WM_DEEPIN_BLUR_REGION_ROUNDED` or `_KDE_NET_WM_BLUR_BEHIND_REGION`, the blur will works.

If you know any other wm has its own blur support other than these two, feel free to let us know or submit a patch to make deepin-termnal better!

**Comment by I-Love-My-Ex** [comment]
ok thank you i didn't know i need those
well imma close this now..
