### ISSUE TITLE
深度终端无法调整窗口大小

### ISSUE THREAD

**Issue by widon1104** [martyr-deepin/deepin-terminal-gtk#173]
只能最大化，最小化，无法自己调整终端大小，这个很不人性化，而且默认终端窗口太小了，连个top信息都显示不全

**Comment by BLumia** [comment]
请问您所使用的发行版和窗口管理器是？

深度终端是支持调整大小的，但由于本身是自绘边框处理窗口大小调整逻辑的，所以在部分窗口管理器中触发边框调整大小的边缘可能过窄（Deepin 保证在 deepin-wm 和 dde-kwin 中调整边框使用正常）。所以希望你可以提供更详细的信息。

另外，大多数层叠式窗口管理器默认都提供了 Alt+鼠标右键拖动 来调整窗口大小的功能（ps. Deepin 发行版默认禁止了这个行为），如果你的窗口管理器具备并启用了此功能，可以尝试通过此功能更便捷的调整窗口大小。

**Comment by widon1104** [comment]
我使用的是deepin15.10.1，所有软件是最新的。
Screenfetch的结果WM: KWin，窗口管理器是KWin
我说无法调整终端窗口大小的意思是，光标放在窗口边缘，没有提示修改窗口大小的提示，也就无法调整窗口大小。我把光标很缓慢的在窗口（上、下、左右都试过）边缘移动没有任何反应。
我试了一下Alt+鼠标右键是可以调整窗口大小的，但是可能有很多人不知道这个快捷键，所以希望修复这个问题。

**Comment by BLumia** [comment]
请问您使用 KWin 是否开启了混成？

**Comment by widon1104** [comment]
我把窗口特效打开（没有选择3D或者2D的界面），可以用调整深度终端窗口大小了。我希望就算不开特效也能工作正常，因为我的电脑比较老，不希望系统变得卡顿。

**Comment by BLumia** [comment]
那这个是已知情况了，可以考虑实机安装而不是虚拟机，安装系统时提示的建议实机安装获得更好的体验其实这个是原因之一。

另外我尝试看过一次相关代码，不过由于我不熟悉 vala/GTK 所以没有修改相关的地方，最终是在 dde-kwin 那边处理的窗口边缘相应区域的大小（但仅限开启混成的情况）。如果有社区贡献者有兴趣完善非混成情况的支持的话，欢迎直接发起 PR 。
