### ISSUE TITLE
深度终端无法识别我安装在系统的字体

### ISSUE THREAD

**Issue by widon1104** [martyr-deepin/deepin-terminal-gtk#174]
我在~/.fonts/下面安装了一款点阵字体叫Zfull gb，但是深度终端无法找到这款字体，也就无法设置终端字体为Zfull gb

**Comment by BLumia** [comment]
非等宽字体会被过滤不可选择，以及如果您使用 DDE 的话，请尝试从控制中心查找确认你的字体是否安装正确。

**Comment by widon1104** [comment]
字体安装肯定没有问题，我已经在个性化-》标准字体设置成我安装的点阵字体 Zfull-gb了。
希望深度终端不要自作聪明过滤字体，Zfull-gb这款字体作为终端字体非常好，英文字母是等宽的、中文是点阵，显示效果好。
我使用gnome-terminal Terminator都可以设置字体为Zfull gb就深度终端不行

**Comment by BLumia** [comment]
过滤非等宽字体目前大概是属于产品需求定义里的，不经过产品确认大概不会随便修改这个行为，回头会找产品讨论一下。

另外，终端的配置文件存储在 `~/.config/deepin/deepin-terminal/config.conf` 中，你可以通过修改这个文件的方式指定所使用的字体。

**Comment by abcfy2** [comment]
有些等宽字体的确不会出现在终端的字体选择器中，疑似元数据中没有。

比如我添加了`Monaco`这款字体，这款字体是MacOS下终端的等宽字体，但是在Deepin终端中就没有这个字体。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
