### ISSUE TITLE
could add new feature for show and hide termial of hot keys.

### ISSUE THREAD

**Issue by alukaa** [martyr-deepin/deepin-terminal-gtk#178]
as the title,if there is plan of add hot keys for show and hide the termial,  may like the way of the [Conemu](https://conemu.github.io/). i think it will be useful.

**Comment by BLumia** [comment]
Sorry I don't understand the `hide` behavior, what does `hide` means, did you means if we opened a tab, we can hide the tab and show the tab later?

**Comment by alukaa** [comment]
something like
