### ISSUE TITLE
Blurred background

### ISSUE THREAD

**Issue by marcinciarka** [martyr-deepin/deepin-terminal-gtk#18]
Is this possible?

**Comment by manateelazycat** [comment]
Patch has implement this feature: https://github.com/linuxdeepin/deepin-terminal/commit/53a9ae29a2be43f04796115f6f93c3023ac5d40a

After compile newest version, click "blur background" option
![_ _20171127155614](https://user-images.githubusercontent.com/237487/33257826-8949c20c-d392-11e7-93dc-86fa5039ba6e.png)

**Comment by RocketLR** [comment]
I just did a fresh install of Deepin 15.10 on two seperate machines. And on both of them the blur does not take effect after i turn it on in the settings menu. 
Any suggestions how to fix this?
