### ISSUE TITLE
CTRL+ALT+T会被打印到终端上

### ISSUE THREAD

**Issue by abcfy2** [martyr-deepin/deepin-terminal-gtk#182]
Deepin-terminal的开启新标签的快捷键为`CTRL` + `ALT` + 'T'。但是按下之后会发现这个健会被打印到终端上，而不是先被deepin-terminal捕获

![image](https://user-images.githubusercontent.com/5327677/61439949-0e700180-a975-11e9-975b-508d81dbf8b7.png)

这样在很多地方都非常碍事，比如vim编辑的时候就会出现这个问题

![image](https://user-images.githubusercontent.com/5327677/61440053-3fe8cd00-a975-11e9-92a1-508a0f1f667d.png)

而这个问题只有Deepin-terminal独占，其他所有的虚拟终端我都没遇到这个问题，希望予以修复。

**Comment by BLumia** [comment]
我在目前的 Deepin stable 上没有复现正常等待输入指令的情况也会插入 `^T` 的这个问题（使用的 shell 是 bash ），不过可以复现 vim 编辑状态按下会插入制表符的问题。

有时间研究一下，我实在是 vala 苦手（摊手）。

**Comment by BLumia** [comment]
assoc: https://github.com/linuxdeepin/developer-center/issues/712

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
