### ISSUE TITLE
打开窗口再关闭造成终端滚轮失灵

### ISSUE THREAD

**Issue by abcfy2** [martyr-deepin/deepin-terminal-gtk#185]
具体重现方法不明。

经常会遇到这样的现象，就是滚轮失灵，无法通过滚轮（或触摸板双指）翻动终端，只能用鼠标点击拖动右边的滚动条进行翻动终端。

似乎让终端失去焦点，再切换回来重新获得焦点这个问题又得以修复。

**Comment by abcfy2** [comment]
我找到了重现的方案了，打开前台程序再立即关掉就会遇到这个BUG。而打开前台程序，切换过焦点的话就不会

[深度录屏_deepin-terminal_20190730214130.mp4.zip](https://github.com/linuxdeepin/deepin-terminal/files/3447037/_deepin-terminal_20190730214130.mp4.zip)

**Comment by BLumia** [comment]
内部也有偶然遇到过这个问题，不过还没具体定位问题。

**Comment by abcfy2** [comment]
> 内部也有偶然遇到过这个问题，不过还没具体定位问题。

我发现的重现方式是打开一个窗口程序，立即关掉就会遇到这个问题，产生的原因不明

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
