### ISSUE TITLE
Default Terminal in Ubuntu 19.04

### ISSUE THREAD

**Issue by biswajitpaul01** [martyr-deepin/deepin-terminal-gtk#186]
How can I replace it as default terminal in Ubuntu 19.04? So that when I right click and select "Open in Terminal" in menu, it opens up automatically.

**Comment by BLumia** [comment]
I'm not sure which file manager application you are using, but you can try `sudo update-alternatives --config x-terminal-emulator`.

Also, do a google search first is recommended, let us know with more information provided so we can help you out :)

**Comment by biswajitpaul01** [comment]
I am using default file manager in Ubuntu. Below is my terminal screenshot after running the command:

![DeepinScreenshot_gnome-terminal-server_20190801222245](https://user-images.githubusercontent.com/693180/62312229-49148680-b4ab-11e9-8923-d17b03e625d9.png)

![DeepinScreenshot_select-area_201908012229451](https://user-images.githubusercontent.com/693180/62312485-eb346e80-b4ab-11e9-8256-1229da45f35d.png)

**Comment by BLumia** [comment]
Try something like `sudo update-alternatives --set x-terminal-emulator /usr/bin/deepin-terminal` and try `sudo update-alternatives --config x-terminal-emulator`again?

**Comment by biswajitpaul01** [comment]
I got this error:

![DeepinScreenshot_gnome-terminal-server_20190802221013](https://user-images.githubusercontent.com/693180/62385318-65c7c180-b572-11e9-84cb-23e651e92d6a.png)

**Comment by BLumia** [comment]
Oops, seems you need to register deepin-terminal to the alternatives list first. 

Basicly `/etc/alternatives/x-terminal-emulator` is just a simple symlink to the default termnal emulator  binary file location and update the link to deepin-terminal should works. But if you want to do this in a more debian way(since `update-alternatives` is a debian-based-distro only thing), consider read the man page of `update-alternatives` and see what you should do next.

**Comment by biswajitpaul01** [comment]
Hi @BLumia 

Thank you for your response. I searched it and found out this command: 
`sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/deepin-terminal 50`

Then I run below to set the terminal:
`sudo update-alternatives --config x-terminal-emulator`

It works with shortcut key Ctrl+Alt+T but not inside file manager right click menu. You may comment more if you found new solution, but now I am closing this issue.

Thanks again.

**Comment by BLumia** [comment]
I'm not using ubuntu/gnome now so cannot try it by myself but maybe [this page](https://askubuntu.com/questions/76712/setting-nautilus-open-terminal-to-launch-terminator-rather-than-gnome-terminal) can helps :)

**Comment by netochaves** [comment]
The @biswajitpaul01 solution works fine, thanks.
