### ISSUE TITLE
Cannot see settings in Gnome 3 dark mode.

### ISSUE THREAD

**Issue by ZGainsforth** [martyr-deepin/deepin-terminal-gtk#190]
When using darkmode on Gnome 3 (Pop OS, Debian family) the settings window text does not show.

Here is what the settings window looks like with dark mode on:

![image](https://user-images.githubusercontent.com/6864619/63209258-42813400-c093-11e9-97df-762d1d5e78de.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
