### ISSUE TITLE
复制时结果不对

### ISSUE THREAD

**Issue by hebw** [martyr-deepin/deepin-terminal-gtk#194]
例子：
echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-security main restricted universe multiverse" > /etc/apt/sources.list

echo "deb http://mirrors.aliyun.com/ubuntu/ trusty-security main restricted universe /etc/apt/sources.listmultiverse" >

版本：3.2.7.1

**Comment by BLumia** [comment]
看着像是你用的 shell 或者当前的 shell prompt 比较奇怪的缘故，终端本身（或者说 VTE）并不会干预复制的内容的。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
