### ISSUE TITLE
No window shadow and no resizing since deepin-kwin

### ISSUE THREAD

**Issue by DasJott** [martyr-deepin/deepin-terminal-gtk#196]
Since the switch to deepin-kwin there is no shadow around the terminal window anymore and thus and resizing the window is also not possible anymore.
That is of course very annoying.

**Comment by BLumia** [comment]
I'm not quite sure since I don't have a clean environment to test this issue (Me on Deepin with debian buster based package repo works fine), but maybe you can backup and delete your kwinrc file (`~/.config/kwinrc`), re-enter a new DDE session and check if it fixes your issue.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
