### ISSUE TITLE
No support for ssh-agent

### ISSUE THREAD

**Issue by Daemoen** [martyr-deepin/deepin-terminal-gtk#197]
When attempting to connect to a host under remote management, you can set a password, or supply a certificate/pem key.  If you do not specify either, you would think that it uses the ssh-agent, but it doesn't.  In fact, it explicitly sets -o PubkeyAuthentication=no during the connection string, as seen:

```
spawn zssh -X -o ServerAliveInterval=60 daemoen@daemoen.somehost.com -p 22 -o PubkeyAuthentication=no -t echo Welcome to Deepin Terminal, please make sure that rz and sz commands have been installed in the server before right clicking to upload and download files. && exec $SHELL -l
Press ^@ (C-Space) to enter file transfer mode, then ? for help
```

Unfortunately, this means that those of us that use ssh-agent only connections, or even hardware token authentication -- remote management logins are useless.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
