### ISSUE TITLE
quake mode problems in ubuntu 18.04

### ISSUE THREAD

**Issue by NanerLee** [martyr-deepin/deepin-terminal-gtk#198]
在 Ubuntu 18.04.3 中使用 apt 安装的deepin-terminal, 可以使用 -q 参数启动 quake 模式, 但是其它方式不行
1. 右键左上角的图标, 什么都没有
2. alt+f2(已经禁用系统的快捷键, 在普通模式下的深度终端内按下此快捷键会输入"Q")

另外还有一些建议
1. quake 模式能够单独设置快捷键来显示和隐藏
2. quake 模式下希望终端可以不一直显示在顶层

**Comment by BLumia** [comment]
右键图标本来也什么都没有，一直都这样的。第二个问题如果你的预期是调起雷神模式的话，你需要配置你的系统快捷键才行。普通窗口的终端本身不进行唤起雷神终端的功能。

关于建议1，如果在开启雷神终端的时候再次运行-q就是隐藏雷神终端了，你可以通过绑定快捷键触发运行 `deepin-terminal -q` 实现这个需求（不过之前有处理过相关bug，在 kwin 上不会隐藏的问题，后续修复了，不过 ubuntu 18.04 的版本可能没有这个修复，手动编译或者等发行版软件包维护者更新就行了）。至于2，目前设计上就是置顶的，暂时不会考虑加。

**Comment by NanerLee** [comment]
@BLumia 感谢回复

我在 deepin 的 wiki 上看到的是右键图标可以选择雷神模式的, 可能 ubuntu 上没有

关于 alt+f2  我大概明白了, 估计是 deepin 默认就设置了这个快捷键

对于第二个建议, 这个其实有争议, guake 就可以支持, tilix(terminator) 不支持, 不过我也提过 issue 希望增加一个选项, 好像还没进展. 非置顶有时还是很有用的

**Comment by BLumia** [comment]
可能 wiki 说的是早期版本，目前 deepin 所附带的终端右键图标也是没有任何作用的，就只是个图标。

第二个这个如果社区有人有意愿提供 patch 增加这个选项支持的话我挺乐意帮助 review 代码和合并的，不过由于时间精力原因，以及我一直都不怎么熟悉 vala 开发，所以目前我们只是修一些新发现的终端的 bug 以及合并一部分社区的 PR，暂时不会有官方引入的新特性加进来。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
