### ISSUE TITLE
Build failed on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by hillwoodroc** [martyr-deepin/deepin-terminal-gtk#201]
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/window.vala:462.120-462.188: warning: unhandled error `GLib.KeyFileError'
[   60s]             if (Utils.is_tiling_wm() || screen_monitor.is_composited() || window_is_fullscreen() || window_is_max() || config.config_file.get_boolean("advanced", "always_hide_resize_grip")) {
[   60s]                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/window.vala:64.13-64.39: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/window.vala:58.36-58.101: warning: unhandled error `GLib.KeyFileError'
[   60s]             tabbar_at_the_bottom = config.config_file.get_boolean("advanced", "tabbar_at_the_bottom");
[   60s]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build'
[   60s] cd /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1 /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1 /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/CMakeFiles/zh_CN.dir/DependInfo.cmake
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/confirm_dialog.vala:102.13-102.38: warning: Gtk.Container.set_focus_chain has been deprecated since 3.24
[   60s] yes
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/./main.vala:41.5-41.20: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
[   60s]     public void exit() {
[   60s]     ^^^^^^^^^^^^^^^^
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/search_panel.vala:149.17-149.47: warning: Vte.Terminal.search_set_gregex has been deprecated since 0.46
[   60s] Scanning dependencies of target zh_CN
[   60s] checking for sys/cdefs.h... make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build'
[   60s] make -f CMakeFiles/zh_CN.dir/build.make CMakeFiles/zh_CN.dir/build
[   60s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build'
[   60s] [ 49%] Generating zh_CN-deepin-terminal.gmo
[   60s] cd /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1 && /usr/bin/msgfmt -o /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/zh_CN-deepin-terminal.gmo po/zh_CN/LC_MESSAGES/deepin-terminal.po
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/remote_panel.vala:229.13-229.35: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build'
[   60s] yes
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/remote_server_dialog.vala:411.13-411.32: warning: Gtk.Window.set_default_geometry has been deprecated since 3.20
[   60s] [ 49%] Built target zh_CN
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/remote_server_dialog.vala:397.17-397.42: warning: Gtk.Container.set_focus_chain has been deprecated since 3.24
[   60s] checking for sys/param.h... /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/remote_panel.vala:161.13-161.41: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/remote_panel.vala:162.13-162.42: warning: Gtk.Widget.margin_right has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/remote_panel.vala:345.17-345.39: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:693.17-693.41: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:669.17-669.40: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:760.17-760.39: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] yes
[   60s] checking for util.h... no
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/rename_dialog.vala:108.13-108.38: warning: Gtk.Container.set_focus_chain has been deprecated since 3.24
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/config_window.vala:578.29-578.55: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
[   60s] checking for stropts.h... /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/command_dialog.vala:224.17-224.42: warning: Gtk.Container.set_focus_chain has been deprecated since 3.24
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/command_panel.vala:131.13-131.42: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/command_panel.vala:132.13-132.43: warning: Gtk.Widget.margin_right has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/command_panel.vala:193.17-193.39: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:727.13-727.36: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:735.13-735.36: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:769.13-769.35: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:777.13-777.35: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:805.13-805.38: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:813.13-813.38: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:787.13-787.37: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] no
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:795.13-795.37: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/workspace.vala:718.17-718.42: warning: Gtk.Widget.margin_left has been deprecated since 3.12
[   60s] checking for tgetent in -ltermcap... /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/terminal.vala:1125.30-1125.50: warning: Vte.Terminal.match_add_gregex has been deprecated since 0.46
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/terminal.vala:1252.25-1252.39: warning: Vte.Terminal.spawn_sync has been deprecated since 0.48
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/terminal.vala:1185.25-1185.39: warning: Vte.Terminal.spawn_sync has been deprecated since 0.48
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/quake_window.vala:47.13-47.39: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/quake_window.vala:462.13-462.39: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/quake_window.vala:286.34-286.61: warning: Gdk.Screen.get_monitor_at_window has been deprecated since 3.22
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/quake_window.vala:289.13-289.39: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/./main.vala:59.5-59.28: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
[   60s]     public void show_or_hide() {
[   60s]     ^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/./main.vala:258.17-258.42: warning: Gtk.Window.set_has_resize_grip has been deprecated since 3.14
[   60s] xcb.vapi:375.3-375.40: error: missing return statement at end of subroutine body
[   60s] 		public VoidCookie image_text_8_checked (Drawable drawable, GContext gc, int16 x, int16 y, string text) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] xcb.vapi:381.3-381.32: error: missing return statement at end of subroutine body
[   60s] 		public VoidCookie image_text_8 (Drawable drawable, GContext gc, int16 x, int16 y, string text) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] xcb.vapi:413.3-413.48: error: missing return statement at end of subroutine body
[   60s] 		public AllocNamedColorCookie alloc_named_color (Colormap cmap, string name) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] xcb.vapi:419.3-419.58: error: missing return statement at end of subroutine body
[   60s] 		public AllocNamedColorCookie alloc_named_color_unchecked (Colormap cmap, string name) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] xcb.vapi:441.3-441.45: error: missing return statement at end of subroutine body
[   60s] 		public VoidCookie store_named_color_checked (ColorFlag flags, Colormap cmap, uint32 pixel, string name) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] xcb.vapi:447.3-447.37: error: missing return statement at end of subroutine body
[   60s] 		public VoidCookie store_named_color (ColorFlag flags, Colormap cmap, uint32 pixel, string name) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] xcb.vapi:458.3-458.39: error: missing return statement at end of subroutine body
[   60s] 		public LookupColorCookie lookup_color (Colormap cmap, string name) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] xcb.vapi:464.3-464.49: error: missing return statement at end of subroutine body
[   60s] 		public LookupColorCookie lookup_color_unchecked (Colormap cmap, string name) {
[   60s] 		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   60s] no
[   60s] checking for tgetent in -lcurses... no
[   60s] checking for tgetent in -lncurses... /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/widget/window.vala:530.22-530.35: warning: local variable `is_light_theme' declared but never used
[   60s]                 bool is_light_theme = is_light_theme();
[   60s]                      ^^^^^^^^^^^^^^
[   60s] Compilation failed: 8 error(s), 55 warning(s)
[   60s] yes
[   60s] checking which library has the termcap functions... using libncurses
[   60s] checking for readline/readline.h... make[2]: *** [CMakeFiles/deepin-terminal.dir/build.make:126: main.c] Error 1
[   60s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build'
[   60s] make[1]: *** [CMakeFiles/Makefile2:740: CMakeFiles/deepin-terminal.dir/all] Error 2
[   60s] make[1]: *** Waiting for unfinished jobs....
[   60s] yes
[   60s] checking for readline/history.h... yes
[   60s] checking for readline in -lreadline... yes
[   60s] checking for rl_username_completion_function... yes
[   60s] checking whether getpgrp takes no argument... yes
[   60s] checking return type of signal handlers... void
[   60s] checking for strdup... yes
[   60s] checking for getpt... yes
[   60s] checking for isastream... no
[   60s] checking for tcsetpgrp... yes
[   61s] checking for _getpty... no
[   61s] checking for getpseudotty... no
[   61s] checking for openpty... no
[   61s] checking for grantpt... yes
[   61s] checking for unlockpt... yes
[   61s] checking for pseudo ttys... streams ptys
[   61s] updating cache ./config.cache
[   61s] creating ./config.status
[   61s] creating Makefile
[   61s] creating fake_readline/Makefile
[   61s] creating test/Makefile
[   61s] creating config.h
[   61s] cd /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/3rdparty/zssh-1.5c && /usr/bin/cmake -E touch /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/zssh-1.5c-prefix/src/zssh-1.5c-stamp/zssh-1.5c-configure
[   61s] [ 50%] Performing build step for 'zssh-1.5c'
[   61s] cd /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/3rdparty/zssh-1.5c && make
[   61s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/3rdparty/zssh-1.5c'
[   61s] make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[   61s] echo '#define ZSSH_VERSION "' `cat VERSION` '"' > version.h
[   61s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o completion.o completion.c
[   61s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o doit.o doit.c
[   61s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o escape.o escape.c
[   61s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o escape_multi.o escape_multi.c
[   61s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o globbing.o globbing.c
[   61s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o init.o init.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o main.o main.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o misc.o misc.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o openpty.o openpty.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o pc_test_escapes.o pc_test_escapes.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o quote_removal.o quote_removal.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o signal.o signal.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o split_words.o split_words.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o tilde_expansion.o tilde_expansion.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o util.o util.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o zmodem.o zmodem.c
[   62s] gcc -g -O2 -Wall -DHAVE_CONFIG_H    -c -o zmodem_act.o zmodem_act.c
[   62s] gcc -o zssh  completion.o doit.o escape.o escape_multi.o globbing.o init.o main.o misc.o openpty.o pc_test_escapes.o quote_removal.o signal.o split_words.o tilde_expansion.o util.o zmodem.o zmodem_act.o -lreadline  -lncurses   
[   62s] make[3]: [Makefile:74: ztelnet] Error 1 (ignored)
[   62s] ln zssh ztelnet
[   62s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/3rdparty/zssh-1.5c'
[   62s] cd /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/3rdparty/zssh-1.5c && /usr/bin/cmake -E touch /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/zssh-1.5c-prefix/src/zssh-1.5c-stamp/zssh-1.5c-build
[   62s] [ 51%] No install step for 'zssh-1.5c'
[   62s] cd /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/3rdparty/zssh-1.5c && /usr/bin/cmake -E echo_append
[   62s] cd /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/3rdparty/zssh-1.5c && /usr/bin/cmake -E touch /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/zssh-1.5c-prefix/src/zssh-1.5c-stamp/zssh-1.5c-install
[   63s] [ 51%] Completed 'zssh-1.5c'
[   63s] /usr/bin/cmake -E make_directory /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/CMakeFiles
[   63s] /usr/bin/cmake -E touch /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/CMakeFiles/zssh-1.5c-complete
[   63s] /usr/bin/cmake -E touch /home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build/zssh-1.5c-prefix/src/zssh-1.5c-stamp/zssh-1.5c-done
[   63s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build'
[   63s] [ 51%] Built target zssh-1.5c
[   63s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/deepin-terminal-3.2.7.1/build'
[   63s] make: *** [Makefile:133: all] Error 2
[   63s] error: Bad exit status from /var/tmp/rpm-tmp.5cxtAV (%build)
[   63s]

**Comment by romildo** [comment]
I am getting this error on NixOS too.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
