### ISSUE TITLE
是否可以增加选中文字时Ctrl-C的行为变成复制

### ISSUE THREAD

**Issue by unrollable** [martyr-deepin/deepin-terminal-gtk#203]
虽然可以设置选中即复制，但无论windows还是linux在PC端大部分场景下ctrl-C复制的功能已经深入人心，有时选中字符时还是会下意识的按ctrl-C，这样会把当前的进程关掉
如果能够根据是否有选中文字来改变ctrl-C行为，体验会很好

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
