### ISSUE TITLE
Support Azure AD login

### ISSUE THREAD

**Issue by ratcashdev** [martyr-deepin/deepin-terminal-gtk#204]
Azure AD login generates usernames like `username@domain.com` and thus the ssh string for login looks like this:
`ssh username@domain.com@host.or.ip:port`
The RemoteManagement panel in such cases always considers the part after the first `@` the hostname, which is wrong. 
Regular SSH works.

Entries in the `server-config.conf` then look like this:
`[user.name@domain.com@10.20.30.40@22]` but the app is not able to correctly parse this and sets `user.name` as the user (incorrectly), considers `domain.com` the hostname and `10` as the port. The rest is dropped.

**Comment by ratcashdev** [comment]
Maybe using a different separator (e.g. `|` instead of `@`) in https://github.com/linuxdeepin/deepin-terminal/blob/77546a4653ec17e36f5b7b2d5588c7dc78a960c8/widget/remote_panel.vala#L291 would help?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
