### ISSUE TITLE
建议终端添加一个鼠标单击 文件路径字符串 就可以打开文件功能

### ISSUE THREAD

**Issue by oooreadooo** [martyr-deepin/deepin-terminal-gtk#208]
使用终端的时候,打开文件应该是最常用的操作,打开文件一般操作步骤是输入:
1.输入编辑器  2.文件路径文件名  3.指定打开直接跳到文件具体哪一行  然后+enter 即可打开文件.
而文件路径往往是复制粘贴得到的.
其实这些步骤,我认为太麻烦了,添加了我说的功能之后都可以省略.我在ubuntu的的终端源码上面修改出了这些功能,感觉对平时工作帮助实在太大了.

这个想法的来源是,在使用终端的过程中,终端能自动识别出http链接,然后strl+鼠标单击打开http链接,那么为什么不能单击打开文件呢?其实做完美了,其实还能打开文件跳到指定的行.
例如:
hds@hds-VirtualBox:~/桌面/hdsout$ grep -rnH hds src/terminal-screen.c 
src/terminal-screen.c:131://.hds.i20190730 add for hdschange start
src/terminal-screen.c:134://.hds.i20190730 add for hdschange end
src/terminal-screen.c:262:{ //hds
src/terminal-screen.c:263:	FILE *fp = fopen("/home/hds/桌面/config.txt", "r");
src/terminal-screen.c:555:		hdslog("/usr/bin/vim exist");
src/terminal-screen.c:560:		hdslog("/usr/bin/vim not exist");
src/terminal-screen.c:565:		hdslog("/usr/bin/code exist");
src/terminal-screen.c:570:		hdslog("/usr/bin/code not exist");

上面得到的查询结果,文件路径后面都是带着行号的.其实可以做到单击就可以跳到指定的行的

**Comment by oooreadooo** [comment]
要具体了解我的idea,可以到:https://github.com/oooreadooo/hds_best_terminal
这里有视频介绍,也有软件安装试用

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
