### ISSUE TITLE
Is there a way to get information about a split pane from another pane?

### ISSUE THREAD

**Issue by iyuvalk** [martyr-deepin/deepin-terminal-gtk#209]
Hi,

I have just installed deepin-terminal and it certainly looks like Terminator on steroids (-: 
Thanks a lot!
 
I couldn't find any link to a forum or another place to ask this question. Is it possible to get from the command line in one pane information such as the current process and folder in the other pane? for example, if in one pane I'm at /home/yuval/a/b/c running nano and in the other pane I'm at /home/yuval is it possible from this pane to get the current working directory in the other pane (/home/yuval/a/b/c) and the current process (nano)?

While I'm already on this, is it possible to split the current window vertically and horizontally by running a command in the current window?

Thanks a lot,
Yuval

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
