### ISSUE TITLE
快捷键识别错误 ctrl + shift + t 也同时触发了ctrl + t 的功能

### ISSUE THREAD

**Issue by 0x8f701** [martyr-deepin/deepin-terminal-gtk#212]
在安装fzf之后，gnome-terminal中ctrl+shift+t不会错误触发ctrl+t的功能(fzf搜索)，然而在deepin-terminal中会。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
