### ISSUE TITLE
请求超链接支持

### ISSUE THREAD

**Issue by nios34** [martyr-deepin/deepin-terminal-gtk#215]
GNOME Terminal 和其它一些 基于VTE的终端模拟器 已经支持超链接，请求加入超链接支持！

提案： https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

**Comment by BLumia** [comment]
~~我们本来就支持啊~~，目前的 deepin-terminal 本来也就是基于 vte 的..

edit: 哦不对，我再确认一下，看看是不是需要开什么选项。

**Comment by BLumia** [comment]
备注：需要通过 `vte_terminal_set_allow_hyperlink()` / [`Vte.Terminal.set_allow_hyperlink()`](https://valadoc.org/vte-2.91/Vte.Terminal.set_allow_hyperlink.html) 启用这种支持，并在点击链接时通过 `vte_terminal_hyperlink_check_event()` 检查相应点击获得链接位置。可供测试的示例：`printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'`

**Comment by BLumia** [comment]
目前 `master` 分支已增加此特性（默认关闭，需要通过配置文件启用），如果有需求的话建议自行拉取代码编译使用。预计下次推送 tag 至少得到下个月了。
