### ISSUE TITLE
how to replace the deepin-menu with the default menu from GTK ?

### ISSUE THREAD

**Issue by adierebel** [martyr-deepin/deepin-terminal-gtk#22]
how to replace the deepin-menu with the default menu from GTK?
from `lib/menu.vala` I can see that the menu list is called by proxy. so, if there is no deepin-menu there is no menu list. Deepin-meu is beautyful but its painful when installing on ubuntu. So, i want to replace deepin menu with GTK default menu. but, how ?

**Comment by adierebel** [comment]
Replace deepin-menu using `Gtk.Menu()`

Solved

**Comment by asrcraft** [comment]
I do not understand,how to do it?Thanks very much
