### ISSUE TITLE
打印emoji字符时会卡死

### ISSUE THREAD

**Issue by xyz327** [martyr-deepin/deepin-terminal-gtk#23]
打印服务器输出日志时，如果日志中有emoji表情会卡在emoji表情字符那里，不会继续打印日志

![image](https://user-images.githubusercontent.com/6970681/31040597-bea5ff42-a5bb-11e7-8375-56a3470ac190.png)
在gnome-terminal上可以正确显示
![image](https://user-images.githubusercontent.com/6970681/31040653-59bce4be-a5bc-11e7-86fe-b19d3a9e638c.png)

**Comment by manateelazycat** [comment]
git 最新版本已经修复了 emoji 表情包的问题了。
![_deepin-terminal_20171014202030](https://user-images.githubusercontent.com/237487/31575623-a3429a7c-b11d-11e7-8a0f-5ac2d00472f3.gif)
