### ISSUE TITLE
Theme change?

### ISSUE THREAD

**Issue by ghost** [martyr-deepin/deepin-terminal-gtk#231]
DDE UI changed. Now:

![Screen Capture_deepin-terminal_20200614154501](https://user-images.githubusercontent.com/65664227/84587967-2c303a00-ae56-11ea-8a64-dcc489b56237.png)

Was:

![Screen Capture_deepin-terminal_20200529035009](https://user-images.githubusercontent.com/65664227/84587985-4f5ae980-ae56-11ea-83aa-3d09414a27ea.png)

I hope this is not a permanent change.

Environment:
- Arch Linux
- DDE 20 beta rolling
- deepin-terminal 5.2.2.20200601-1

**Comment by ghost** [comment]
Likely cause: https://github.com/linuxdeepin/deepin-terminal/issues/230

**Comment by felixonmars** [comment]
The old terminal has been packaged as `deepin-terminal-old` in Arch.

**Comment by ghost** [comment]
That's a good solve for the peeps who loved the old terminal. Thanks for sharing @felixonmars
