### ISSUE TITLE
[Feature] run as login shell

### ISSUE THREAD

**Issue by coffeeneer** [martyr-deepin/deepin-terminal-gtk#24]
First off, I really like this project. It certainly is one of the most beautiful terminals, love the combination of a regular window and quake like drawer.

There is one feature that I really miss though, that is the ability to launch the default shell as a login shell.
I'm using bash as a default shell for my user account, but since the shell is not launched as login shell the ~/.bash_profile is not sourced (as well as ~/bin) which I would really like to have sourced as a default.

_I have tried to see if I could add this feature myself and put in a PR, but since I have not done any programming with GTK+ or gnome libs I'm having a hard time finding out how._

**Comment by manateelazycat** [comment]
I don't know "how to use login shell"
I glad to add this feature if i understand what's is login shell. ;)

**Comment by coffeeneer** [comment]
@manateelazycat a normal terminal runs the shell as a system shell. For example for bash this means running the binary `/bin/bash` or just `bash`.
A login shell is the same shell but run in a different mode, where the currently logged in user's settings (~/.bash_profile, ~/.profile, ~/.bashrc) are sourced automatically and the ~/bin folder is included in the path.
To start a shell as login shell for most this means adding a - as argument 0, so for bash this would be `- bash` instead of `bash`. In case of bash you can also add `-l` as parameter at the end (like `bash -l`).

Maybe some helpfull info here: https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell

This feature already exists in gnome-terminal, I noticed that project is also build upon the VTE library.
I've found the place where they implemented this: [github link](https://github.com/GNOME/gnome-terminal/blob/1c6f8db736efc62d9a9b38bfbc43ec03c8544696/src/terminal-screen.c#L1148)

Hope this helps!

**Comment by manateelazycat** [comment]
@dodedodo33 Hi, i have build new patch https://github.com/linuxdeepin/deepin-terminal/commit/daa6e0ee3a4e6c20d99ec43ae0b102dd7ac1211f to support login shell feature.

After you compile newest version, just change option "run_as_login_shell" to true in config file ~/.config/deepin/deepin-terminal/config.conf 

Then restart deepin-terminal should work.

I don't use login shell usually，please let me know if have any problem.

**Comment by coffeeneer** [comment]
@manateelazycat Seems to work as expected! Thank you very much for adding this feature, really appreciate it!

**Comment by manateelazycat** [comment]
@dodedodo33 you're welcome. ;)
