### ISSUE TITLE
PuTTy/old X Windows copy/paste possible?

### ISSUE THREAD

**Issue by ktechmidas** [martyr-deepin/deepin-terminal-gtk#25]
Hi,
I haven't seen anything on this...

This is what I mean (from another software:)
"The only thing you need to do, to copy text to the clipboard, is to select it...To paste the clipboard contents by default you click the right mouse button. "

So you just select what you need then it's in your clipboard and you can paste it wherever. Is this possible for deepin terminal too?

**Comment by manateelazycat** [comment]
You just need select text in deepin-terminal, then click *middle* button of mouse.

Above is your need.
