### ISSUE TITLE
transparent mode gets triggered randomly

### ISSUE THREAD

**Issue by pahnin** [martyr-deepin/deepin-terminal-gtk#30]
I have been facing the issue for a long time and it is becoming a bit of annoyance now, randomly when I use the terminal I guess, some shortcut or something gets triggered and the opacity of the terminal changes to 0 which makes everything horrible, I have to go to settings and set opacity to full again, but sometimes when opactiy becomes zero, the mouse hangs and I cant properly click the settings option either, so I have to restart the system. I did look up all the settings and cant find any reason why this is happening.

**Comment by manateelazycat** [comment]
Ctrl + mouse scroll will adjust transparent of terminal.
I guess the reason is that when you press the Ctrl key, the right hand accidentally ran into the laptop touchpad.
