### ISSUE TITLE
Blur option doesn't appear in the last version of Deepin (15.5)

### ISSUE THREAD

**Issue by owengombas** [martyr-deepin/deepin-terminal-gtk#32]
Hello, i made a issue "No blur" but you closed it, it’s my mistake, sorry.
I was reffering to the production version delivred with Deepin 15.5 not the github version on "master" branch. (Because i can't compile it, don't have the librsvg module and i can't install it, i don't know why, if you have a solution to correct this problem, tell me :) )

**Comment by andryNoor** [comment]
I can compile Deepin-terminal "master" branch on my system. Currently I also run Deepin 15.5. Before, I also got error when compile it, but I just install what it needs, follow all that README.md instruction... I install librsvg2-dev and all what it needs to compile.

But, still there's no blur option

**Comment by andryNoor** [comment]
Now I get that blured terminal.. Horeeee :))

after compile it, just edit the config file (~/.config/deepin/deepin-terminal/config.conf) -> change "blur_background=true" get back to your compiled dir (mine is : ~/Downloads/deepin-terminal/build), then execute ./deepin-terminal . Now new deepin-terminal with blured background will show up.

-----
I just copy that file (deepin-terminal) to /usr/bin/ and rename it to deepin-terminal-blur.
But I don't know how to add it to the Launcher entry (I'm a newbie), perhaps anyone knows how to do it

**Comment by ArthurKnoep** [comment]
For adding a launcher entry you need to create a new file call &lt;what you want&gt;.desktop and put it in the folder : /usr/share/applications

```
[Desktop Entry]
Categories=GNOME;GTK;Utility;System;TerminalEmulator;
Comment=Use the command line
Exec=<path to your binary>
Icon=deepin-terminal
Keywords=shell;prompt;command;commandline;
Name=Deepin Terminal
StartupNotify=true
TryExec=deepin-terminal
Type=Application
```
