### ISSUE TITLE
deepin-terminal 捆绑 zssh 情况的疑问及跟进

### ISSUE THREAD

**Issue by hosiet** [martyr-deepin/deepin-terminal-gtk#33]
先前发现 deepin-terminal 捆绑了 zssh，个人感觉有一些改进空间。

zssh 之前在 Deb 系发行版中是完全不可用的状态，这个是清楚的，问题原因在 [Debian Bug 769366](https://bugs.debian.org/769366) 有所体现。我在 Debian 最上游接手并做了修复，现在的最新 zssh 版本是 [1.5c.debian.1-4](http://tracker.debian.org/pkg/zssh)，现在使用应当没有什么问题。

对于 deepin-terminal 中 7afc89ef850038cb0f4dc763b5501d1e2d0ffe6e 这个提交我看了一下，其实这个并不是降级，而是应用了一系列补丁（称为“升级”也许更好），这些补丁 Debian 上游的版本应当都有（请见 [Debian 上游的补丁目录](https://sources.debian.org/src/zssh/1.5c.debian.1-4/debian/patches/)） 。如果 deepin-terminal 对 zssh 有什么别的补丁要求，请直接告知我（邮件、 GitHub、在 Debian 交 issue 都行），我会在 Debian 最上游修掉。

@manateelazycat 看一下？

**Comment by manateelazycat** [comment]
@hosiet 不仅仅是debian的问题，我发现大多数发行版的zssh都有问题，而且现在真正用这个工具的人很少，包括发行版本身的的开发者。

深度终端因为直接使用上游zssh导致远程连接失败的问题已经发生过5次了，不想再因为这个问题给用户带来困扰。

很高兴debian上游已经修复了这个问题，但是为了产品在所有发行版的稳定性，还是选择自己包含zssh就像终端自己用一个版本的vte控件一样。

我们尊重上游，也一直努力合并修正到上游，但是考虑到多个发行版本的支持现状，自己包含zssh更多是一个产品稳定性决策，望理解。
