### ISSUE TITLE
[Q] How to specify window-width while opening

### ISSUE THREAD

**Issue by rinav** [martyr-deepin/deepin-terminal-gtk#34]
How can I specify window width and height while using `deepin-terminal --quake-mode`
can I specify width and height in percentage when opening in `quake-mode`

**Comment by manateelazycat** [comment]
@rinav You just can specify height: please look option quake_window_height in READ.md: https://github.com/manateelazycat/deepin-terminal/blob/master/README.md

**Comment by rinav** [comment]
I tried with the following combinations but none are working. Can you help out

    deepin-terminal --quake_window_height 100
    deepin-terminal --quake_window_width 100 
    deepin-terminal --quake_window_width=100
    deepin-terminal --quake-mode --quake_window_width=100
    deepin-terminal --quake-mode --quake_window_width=100 --quake_window_height=100
    deepin-terminal --quake-mode --quake_window_width 100 --quake_window_height 100
    deepin-terminal --quake-mode --window_width 100 --quake_window_height 100 
    deepin-terminal --quake-mode --window_width 100 --window_height 100 
    deepin-terminal --quake-mode --window_width 100 --quake_window_height=0.5
    deepin-terminal --quake-mode --window_width 100 --quake_window_height 1.5
    deepin-terminal --quake-mode --window_width 100 --quake_window_height 0.5

**Comment by manateelazycat** [comment]
No, please change value of quake_window_height in config file ~/.config/deepin/deepin-terminal/config.conf

Start argument not support quake_window_height

**Comment by rinav** [comment]
Oohh that works, I edited the conf file to control height. However it would be great to control the width too.

**Comment by manateelazycat** [comment]
@rinav I don't know why so many people want control width of quake window.

Why you guys want adjust width of quake window?
