### ISSUE TITLE
[Feature Request] custom commands alias

### ISSUE THREAD

**Issue by damianatorrpm** [martyr-deepin/deepin-terminal-gtk#36]
Best terminal.

custom command can use shortcut but can not be used in terminal as command. Name of shortcuts auto-alias
would be awesome.

**Comment by damianatorrpm** [comment]
another awesome feature would be if custom shortcut side panel can be pinned so it doesn't hide

**Comment by manateelazycat** [comment]
@damianatorrpm Why not use alias in ~/.bashrc ? 

It's perhaps conflict with user's .bashrc config if terminal do that.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
