### ISSUE TITLE
[Feature Request] Layouts for opening multiple hosts and global commands to open terminals

### ISSUE THREAD

**Issue by tkrause** [martyr-deepin/deepin-terminal-gtk#40]
Being an administrator of large server clusters, it would be a great features to be able to create a "layout" or preset of hosts to open all at the same time. 

In addition, it would be a great feature to be able to organize hosts into Folder or Categories. For example, we have a bunch of VMs that I would like to arrange into a VM folder vs our Network equipment like routers and switches.

Lastly, to make it completely. It would be great to have the ability to send the same text input to all terminals specified (should be able to pick from the open terminals or all).

The use case is that we manage many devices and need to be able to update them all at the same time. A similar feature can be found in SuperPutty.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
