### ISSUE TITLE
"Open in terminal" not working.

### ISSUE THREAD

**Issue by SiamSami** [martyr-deepin/deepin-terminal-gtk#41]
If open a folder in Deepin file manager, then right click on an empty space and then click on "Open in terminal" then it doesn't open Deepin terminal anymore. It started happening after updating flatpak.

**Comment by manateelazycat** [comment]
Which operating system are you use?

The best guess is system update glib/gio that glib write fixed terminal list in gio code.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
