### ISSUE TITLE
"Italic" fonts support?

### ISSUE THREAD

**Issue by y9c** [martyr-deepin/deepin-terminal-gtk#42]
![image](https://user-images.githubusercontent.com/5415510/37284910-3b6186f8-2638-11e8-8943-57e5610d8d01.png)

**Comment by egmontkob** [comment]
Deepin-terminal uses VTE for terminal emulation, and VTE supports italic.

Are you perhaps inside screen, tmux, byobu? If so, you should consult their documentation, forums etc. why they mangle italic and how to fix it.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
