### ISSUE TITLE
Terminal blur artifacts

### ISSUE THREAD

**Issue by marcinciarka** [martyr-deepin/deepin-terminal-gtk#44]
It occurs with most of the blurred UI elements (app bar, notifications, terminal background):
https://streamable.com/w7j9s

How to deal with this?

**Comment by manateelazycat** [comment]
Which system are you use?

**Comment by marcinciarka** [comment]
I'm using Ubuntu with dde installed.

**Comment by manateelazycat** [comment]
@sonald Any idea?

**Comment by sonald** [comment]
deepin-wm needs deepin version of cogl and clutter to work, both of which has been patched to support blurring effect of deepin-wm. and I don't know the status of ubuntu with DDE.

**Comment by marcinciarka** [comment]
@sonald thanks for your input. Which versions of these packages should I have?

**Comment by sonald** [comment]
@dreszczyk I'm not sure if ubuntu has these packages. but if you mean source,  deepin-cogl with tag 1.22.5 and deepin-clutter with tag 1.26.2 is what you need.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
