### ISSUE TITLE
Can I specify a configuration file to start the terminal?

### ISSUE THREAD

**Issue by junolym** [martyr-deepin/deepin-terminal-gtk#5]
Can I specify a configuration file to start the terminal?

I want to use the quake terminal with another config file, so that the quake terminal and the normal one can use different themes.

**Comment by keirosang** [comment]
?

2017-05-02 16:50 GMT+08:00 陈俊贤 <notifications@github.com>:

**Comment by junolym** [comment]
Can you help me?  @keirosang
