### ISSUE TITLE
[Feature request] Show on screen with mouse cursor

### ISSUE THREAD

**Issue by marcin-koziol-iteo** [martyr-deepin/deepin-terminal-gtk#50]
Currently quake terminal will appear on screen with focused window. Is it possible to add a configurable option to alter this behavior, to have the window on screen with mouse cursor? (it is a default behavior of Guake terminal)

**Comment by manateelazycat** [comment]
~/.config/deepin/deepin-terminal/config.conf

Change 

follow_active_window=true

to 

follow_active_window=false
