### ISSUE TITLE
Terminal Quake Shortcut to roll up ?

### ISSUE THREAD

**Issue by aiamuzz** [martyr-deepin/deepin-terminal-gtk#52]
Hi,

I have configured 

> Ctrl + `

 as the shortcut to roll down the quake terminal window. Would it be possible to have the same shortcut 

> Ctrl + `

 to exit or roll the quake terminal window back up ?

I mean when i hit `Ctrl + `` it does roll back up, **but its just that its not clean enough** ... there is a stutter as though its not planned that way its acts confused ... If that little stutter before it rolls back up is ironed out and made just as smooth as it rolls down then, it would be so great !!!

**Comment by gchamon** [comment]
I have pinpointed the cause to be `hide_quakewindow_after_lost_focus=true`. Set it to false and you should stop experiencing this issue.

This is just a workaround though, since hide when lose focus is convenient when quake terminal is not fullscreen. Devs should look into it, but the problem is without a doubt this flag, tested it with two different installations and both stopped stuttering when rolling quake up by disabling `hide_quakewindow_after_lost_focus`

**Comment by aiamuzz** [comment]
> I have pinpointed the cause to be `hide_quakewindow_after_lost_focus=true`. Set it to false and you should stop experiencing this issue.
> 
> This is just a workaround though, since hide when lose focus is convenient when quake terminal is not fullscreen. Devs should look into it, but the problem is without a doubt this flag, tested it with two different installations and both stopped stuttering when rolling quake up by disabling `hide_quakewindow_after_lost_focus`

hmmmmm ... i couldn't find the `hide_quakewindow_after_lost_focus` property in `dconf` editor ... is it something thats part of a config file ?


------ edit ------

found it in the config file ... thanks @gchamon ... after setting it to `false` the roll back animation is waaaay better when it was `true` ...

@BLumia ... i think the conflict has been identified by @gchamon ... needs to be fixed to have the same roll back animation even when the `hide_quakewindow_after_lost_focus` is set to `True` ...

**Comment by gchamon** [comment]
yes, sorry I wasn't more precise.

For anyone looking, the setting is in `~/.config/deepin/deepin-terminal/config.conf`, under `[advanced]`.

**Comment by aiamuzz** [comment]
> yes, sorry I wasn't more precise.
> 
> For anyone looking, the setting is in `~/.config/deepin/deepin-terminal/config.conf`, under `[advanced]`.

:) ... seems that the terminal quake window toggle keys are coded properly ... its just that this 'after lost focus' property with 'true' is causing the glitchy animation when rolling up ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
