### ISSUE TITLE
Port forwarding in remote management

### ISSUE THREAD

**Issue by Arkoprabho** [martyr-deepin/deepin-terminal-gtk#53]
Remote management is highly appreciated and makes things a lot easier. It would be nice if we could have an option for port forwarding.
Sample use case: I have a server running Ubuntu 16.04. I use jupyter notebooks quite a lot. Now to do this, I need to use the port 8888 that gets forwarded from the server to my machine.
Currently the way to do this is using ssh command line options. It would be nice if we can add a list of ports we want to map in while configuring the editing the details of the server in remote management

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
