### ISSUE TITLE
Unreadable terminal characters

### ISSUE THREAD

**Issue by lucaCambi77** [martyr-deepin/deepin-terminal-gtk#54]
![deepin_terminal](https://user-images.githubusercontent.com/13840293/40049171-43d9cf9c-5834-11e8-9584-ed4f4c86ef34.png)
I am using antergos distribution that is archlinux + Deepin.
In deeping terminal characters are not easily readable (see attached picture). It looks like they are stuck to each others, making impossible to read.
It could be an issue related to laptop model which is Lenovo Helix2 (2nd Generation).
Could it also be an issue related to archlinux fonts in terminal? How could i address the issue better with archlinux in that case?

Thanks

**Comment by lucaCambi77** [comment]
https://unix.stackexchange.com/questions/273059/strange-character-overlap-in-terminal

**Comment by BLumia** [comment]
What about changing font from the setting dialog?

**Comment by lucaCambi77** [comment]
ok next time i'll face the problem, i'll try for sure changing fonts
and i'll upate the issue

thanks
