### ISSUE TITLE
Deepin Terminal 3.0 is unusable now

### ISSUE THREAD

**Issue by laichiaheng** [martyr-deepin/deepin-terminal-gtk#55]
![deepin _20180517001123](https://user-images.githubusercontent.com/9532105/40130148-c2df6876-5968-11e8-99f7-0cd6b75873f7.png)

**Comment by prscoelho** [comment]
Hello. Same issue here. I hadn't updated my system since March, I finally got the time to update today and upon reboot my terminal looks like this:

![](https://i.imgur.com/2gTdpb3.png)

I'm on archlinux.

**Comment by laichiaheng** [comment]
It has been fixed
