### ISSUE TITLE
Allow building with system dependencies

### ISSUE THREAD

**Issue by jtojnar** [martyr-deepin/deepin-terminal-gtk#59]
Most Linux distributions have policies forbidding the use of vendored dependencies, forcing them to patch the source (see [Arch Linux](https://git.archlinux.org/svntogit/community.git/tree/trunk/remove-vendor.patch?h=packages/deepin-terminal&id=de701614c19c273b98b60fd6790795ff7d8a157e) and [NixOS](https://github.com/NixOS/nixpkgs/blob/a5cd4b26851734a6d49b097d8d4da69b9b51d4a0/pkgs/desktops/deepin/deepin-terminal/default.nix#L24)).

Adding `-DENABLE_SYSTEM_VTE` and `-DZSSH_PATH` flags that would allow using system dependencies would greatly simplify distribution packaging.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
