### ISSUE TITLE
Can't Ctrl+Left Mouse Button to Open URL

### ISSUE THREAD

**Issue by de-conf** [martyr-deepin/deepin-terminal-gtk#60]

**Comment by chenjiageng** [comment]
I see the version is 2.7 on the deepin-terminal interface, but the deepin store version is 3.0.0-1

**Comment by TheBeastLT** [comment]
I have the same problem, is there any fix?

**Comment by de-conf** [comment]
I have given up deepin and become an arch Linux user....

**Comment by kramer65** [comment]
@de-conf - You switched because of this issue? Is this possible in Arch?

Or what were the other reasons to start using arch?

**Comment by de-conf** [comment]
> @de-conf - You switched because of this issue? Is this possible in Arch?
> 
> Or what were the other reasons to start using arch?

Because of arch's aur repository and community and the best Linux wiki documentation
And it took me an hour to build a package and send the aur repository, which is very cool

**Comment by BLumia** [comment]
Already fixed in #100 ;)
