### ISSUE TITLE
Split window separator.

### ISSUE THREAD

**Issue by alextakitani** [martyr-deepin/deepin-terminal-gtk#62]
Is there a way to change the window separator appearance ?

I think its too thin, I find myself trying to find out on which terminal I am many times.

Terminator has a header for each window, and it changes color when active, that helps a lot.

**Comment by aclowkey** [comment]
Please add this. So hard to read with the small divier..

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
