### ISSUE TITLE
w3m image viewing not supported

### ISSUE THREAD

**Issue by linusboyle** [martyr-deepin/deepin-terminal-gtk#63]
hello developers,
when I tried to use w3m-img to view pictures in my deepin-terminal it failed.Other terminal simulators such as urxvt can at least produce a vague graph of the picture.
It seems w3mimgdisplay binary is not supported by dde terminal,and according to other records about problems in terminal image viewing the problem probably comes from xft fonts with antialias enabled

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
