### ISSUE TITLE
Opacity control with the mouse scroll ... Withdrawn ?

### ISSUE THREAD

**Issue by aiamuzz** [martyr-deepin/deepin-terminal-gtk#64]
Hi,

deepin-terminal had a very nice feature to control opacity of the terminal window with 'Ctrl+mouse scroll' ... is this feature withdrawn ? It was a really nice feature pretty handy to view windows behind the terminal window.

Could you please reinstate this missing feature ?

thanks.

**Comment by aiamuzz** [comment]
@BLumia ... @hualet ... long time no response ...

wasn't this option to manage terminal window transparency present earlier on this application ?

It is a very handy option ... especially when you are trying to type commands looking at the browser in the background ... a handy mouse scroll will help look at the browser behind until the commands have been typed ... Could you please reinstate this option with the scroll wheel ?

**Comment by hualet** [comment]
> @BLumia ... @hualet ... long time no response ...
> 
> wasn't this option to manage terminal window transparency present earlier on this application ?
> 
> It is a very handy option ... especially when you are trying to type commands looking at the browser in the background ... a handy mouse scroll will help look at the browser behind until the commands have been typed ... Could you please reinstate this option with the scroll wheel ?

it's always there, I think that is related to https://github.com/linuxdeepin/developer-center/issues/629, your mouse is somehow configured wrongly.

I'll close this one and let's move discussion to https://github.com/linuxdeepin/developer-center/issues/629
