### ISSUE TITLE
[Feature Request] Add support to detatch terminals

### ISSUE THREAD

**Issue by daviddob** [martyr-deepin/deepin-terminal-gtk#65]
The ability to detatch tabs from the current window into a new window is super useful. Gnome-Terminal implements this via a right click on the tab -> detatch terminal. This takes the current tab and makes it its own window. Is this functionality available via an interface or command I have yet to find, or is it unimplemented?

Thanks.

**Comment by nanpuyue** [comment]
It's in the plan.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
