### ISSUE TITLE
[Feature Request] 远程服务器分组信息支持多级分组

### ISSUE THREAD

**Issue by j0ck1e** [martyr-deepin/deepin-terminal-gtk#66]
- 远程服务器分组信息支持多级分组
- 远程服务器支持导入导出
- 右击标签页支持复制会话窗口
- 如果标签页能拖动换位置就更好了

**Comment by wjangelking** [comment]
完全同样的需求！

**Comment by j0ck1e** [comment]
@wjangelking https://github.com/Eugeny/terminus

**Comment by j0ck1e** [comment]
@wjangelking https://github.com/gnunn1/tilix
