### ISSUE TITLE
[Feature Request] 远程管理 add support ssh passphrase

### ISSUE THREAD

**Issue by lixiangzhong** [martyr-deepin/deepin-terminal-gtk#67]
当sshkey 有passphrase时,每次都要手工输入很麻烦

**Comment by BLumia** [comment]
如果只验证带密码的 sshkey 的话，直接在远程管理输入密码的位置输入你的 sshkey 的 passphrase 应该就可以了。

相关代码：
https://github.com/linuxdeepin/deepin-terminal/blob/19f9f9863a596779316409ac8d7c813a40e04f05/ssh_login.sh#L55-L57

**Comment by lixiangzhong** [comment]
thx
