### ISSUE TITLE
[Feature Request] Font ligatures

### ISSUE THREAD

**Issue by 0xF6** [martyr-deepin/deepin-terminal-gtk#68]
Add to terminal support font ligatures. at [FiraCode](https://github.com/tonsky/FiraCode) font

**Comment by nanpuyue** [comment]
It's a bug of upstream:
https://bugzilla.gnome.org/show_bug.cgi?id=584160
https://bugzilla.gnome.org/show_bug.cgi?id=781597

**Comment by nanpuyue** [comment]
It seems that the upstream has been fixed it.

**Comment by 0xF6** [comment]
Okay, how is this related to font ligatures support?

**Comment by arslan2012** [comment]
@nanpuyue 你可能理解错原博主的意思了 ligatures是连体字母， 比如如果你用了带有连体字母能力的字体，比如原博所提到的[FiraCode](https://github.com/tonsky/FiraCode)，那么->则会被自动连接成🠂, <- 会变成🠀, 这个功能在iTerm2，kitty之类的终端上已经有支持了

**Comment by arslan2012** [comment]
@nanpuyue 并且- < > 这些符号都是ascii符号，并不是unicode

**Comment by BLumia** [comment]
@arslan2012 Did vte itself got any support for this feature?

-----

vte 本身支持连字这个特性吗？

**Comment by arslan2012** [comment]
@BLumia sadly, no

since even konsole supports ligature now, there's also a feature request there, but no one from gnome is willing to implement it

**Comment by BLumia** [comment]
So it's still a upstream issue :-/ 

FYI, we used decided to start a new project to rewrite the whole deepin-terminal project in Qt with other lib rather than vte but this project is paused for now.

-------

所以其实还是上游的事..

我们之前是有打算开个用 Qt 和其他更好的库来完全重写终端的坑的，不过现在这个坑暂停了 = =

**Comment by egmontkob** [comment]
> no one from gnome is willing to implement it

This is a bit harsh wording.

We've (VTE developers) expressed some concerns about this feature. We have limited capacity, hundreds of pending issues to work on. We just haven't had the opportunity to work on this one, nor felt like this being the next one we should tackle from the pool.

In the meantime, the current master branch received some changes around how we render stuff, these changes make it noticeably simpler to implement ligatures one day.

> rewrite the whole deepin-terminal project in Qt with other lib

May I kindly ask, mostly for curiosity, and to understand what are the most important areas for us to improve in VTE: What were the main reasons behind this decision? Were they mostly GTK vs. Qt, or to the quality of terminal emulation itself? If the latter, what were your key cons with VTE? Thanks! (I sincerely hope that this decision was not based solely on the lack of ligature support :))

**Comment by BLumia** [comment]
> Were they mostly GTK vs. Qt, or to the quality of terminal emulation itself?

Well it's an old decision. The main purpose is moving from GTK to Qt so when designer change their UI design spec, we will no longer need to implement it twice in GTK. So it's mostly a GTK vs. Qt thing. We're not decided to switch to other terminal emulator from VTE or not since this project is not started. The whole project is paused/cancelled so I don't know too much about the details.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
