### ISSUE TITLE
% (percent symbol) appears when using Oh-My-zsh

### ISSUE THREAD

**Issue by rdrms** [martyr-deepin/deepin-terminal-gtk#70]
Seems to be the exact same issue as https://github.com/zeit/hyper/issues/2144

>This is due to the session shell invoking. Since we print the window before creating the required IPC connectors.

**Comment by YOUR-WORST-TACO** [comment]
I am also getting this behavior on several different terminals, and it seems to be intermittent, ie it only happens about 50% of the time, terminals I have seen that are affected
- termite
- urxvt
- kitty

note I use a few settings in my .zshrc
so I will share them for reference
```
export ZSH="/home/taco/.oh-my-zsh"
export GOPATH=/home/taco/.local/share/go

cat /home/taco/.config/wpg/sequences

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

alias ubuntu-dev='docker run -t -i ubuntu /bin/bash'
alias void-dev='docker run -t -i voidlinux/voidlinux /bin/bash'
alias fedora-dev='docker run -t -i fedora /bin/bash'
alias alpine-dev='docker run -t -i alpine /bin/ash'

alias music='ncmpcpp -c ~/.ncmpcpp/config-art && pkill covart'

alias dots='git --git-dir=$HOME/.dots.git/ --work-tree=$HOME'

##########################################
#
# Prompt
#
##########################################

prompt_error() {
    RETVAL=$?

    if [ ! "$RETVAL" = "0" ]; then
        echo -n "%F{9}$RETVAL%f"
    fi
}

PROMPT=$(
    echo "%F{14}%2~ %f⩽ "
)

RPROMPT='$(prompt_error)'
```

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
