### ISSUE TITLE
When you close one tab, the application exits completely

### ISSUE THREAD

**Issue by DmitrySkibitsky** [martyr-deepin/deepin-terminal-gtk#73]
However, the tab that you close is not a single tab.

Version: 3.0.5

**Comment by DmitrySkibitsky** [comment]
![deepin-screen-recorder_select area_20181003232247](https://user-images.githubusercontent.com/20288556/46437151-55349800-c763-11e8-9998-d74ebfa0a8f7.gif)
As it turned out it works if you close the first tab.

But it seems to me that earlier it happened that I closed not the first tab and with the application still came out.

**Comment by nanpuyue** [comment]
caused by: https://github.com/GNOME/vte/commit/0276859709692ec53f35a8cc158d7553a195c730

**Comment by nanpuyue** [comment]
fixed
