### ISSUE TITLE
[Feature Request] 服务器列表支持方向键选择

### ISSUE THREAD

**Issue by Yealove** [martyr-deepin/deepin-terminal-gtk#75]
现在用快捷键`Ctrl /`后还要用鼠标选择服务器才连接，不方便。
希望加入**方向键选择服务器**的功能，更方便操作

**Comment by happyd0ggie** [comment]
希望支持`ctrl+j/k`在服务器列表上导航

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
