### ISSUE TITLE
Possibility to see which tabs have new output?

### ISSUE THREAD

**Issue by kramer65** [martyr-deepin/deepin-terminal-gtk#77]
In iTerm2 on MacOS it is really easy to see which tabs have new output. In the screenshot below you see that the tabs with a blue dot (the first and third tab) have new output. Is it possible to have something similar in the deepin terminal?

![screen shot 2017-03-04 at 11 59 35 am](https://user-images.githubusercontent.com/596581/41718366-0634b5da-755d-11e8-9345-02c2ed4924e2.png)

I asked this same question in the tilix github here: https://github.com/gnunn1/tilix/issues/1445
That thread includes a long discussion on why it could or could not be possible. Maybe that could help you..

**Comment by hualet** [comment]
Agree with the tilix developer, and I personally prefer what deepin-terminal already do, just show the alert/notification when some command is completed, not when there's new contents, it's annoying I think.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
