### ISSUE TITLE
Keyboard shortcut to clear terminal

### ISSUE THREAD

**Issue by muhammadkholidb** [martyr-deepin/deepin-terminal-gtk#79]
Is there any keyboard shortcut to clear the terminal content like `Ctrl + K` in Mac terminal or `Ctrl + Shift + K` in Linux Mint terminal?

**Comment by rafaeldev** [comment]
Did you try using `Ctrl + L`?

**Comment by muhammadkholidb** [comment]
Tried that. It doesn't clear all the terminal buffer, but only the text currently seen. If you scroll up the terminal it you will see the previous text on the terminal.

**Comment by hualet** [comment]
you can make an alias https://stackoverflow.com/questions/5367068/clear-a-terminal-screen-for-real, and bind a new hotkey for it  http://www.humbug.in/2010/custom-key-bindings-keyboard-shortcuts-in-bash/.

**Comment by abrighton** [comment]
I don't see any keyboard shortcut to clear a terminal while a command is running. On Mac and Gnome it is something like Ctrl-K/Cmd-K. Making an alias is not useful if a command is currently running.
