### ISSUE TITLE
[Feature Request] Clear terminal while a command it is running

### ISSUE THREAD

**Issue by rafaeldev** [martyr-deepin/deepin-terminal-gtk#83]
**What's happing?**e.g:
Try clear terminal (`Ctrl + L`) when a command "lock" the terminal. For example:

```bash
tail -f dummy.txt | grep "abc"
```
After that command if I try clear the terminal the command is avoided (or repressed?) and it shows only a `^L`

Thanks

**Comment by hualet** [comment]
Isn't it the normal behavior in basically all terminal emulators?

**Comment by rafaeldev** [comment]
Sorry for late!

I tried use **Terminator** but not success...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
