### ISSUE TITLE
[Feature Request] Workspace tab move

### ISSUE THREAD

**Issue by karaliux** [martyr-deepin/deepin-terminal-gtk#84]
Hi, it would be nice if I could move the workspace tab to the right or left.

**Comment by hualet** [comment]
You'll can't drag-move the window then.

**Comment by avently** [comment]
@hualet it can be done using Ctrl + drag or drag via right mouse button, for example. So it will not ruin window drag-move

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
