### ISSUE TITLE
Change default 'rename title shortcut' from F2 to another key

### ISSUE THREAD

**Issue by sylank** [martyr-deepin/deepin-terminal-gtk#86]
I am using 3.0.12 Deepin Terminal with 15.8 Deepin desktop Linux. 

When I am using mcedit the save shortcut is F2. Then I want to save and type F2 instead of saving the terminal shows the tab rename dialog. I have changed the default shortcut to nothing but could you change this shortcut to another key by default? 

![deepinscreenshot_select-area_20181220124659](https://user-images.githubusercontent.com/19280914/50283232-89ac1c00-0455-11e9-8ef6-5dc9c881fbaa.png)

Thanks

**Comment by BLumia** [comment]
@wangjia12

**Comment by wangjia12** [comment]
I'm afraid this feature is not in our plan at the moment.

**Comment by sylank** [comment]
okay, clear and what should we do with the pull request?
