### ISSUE TITLE
[Feature Request] Copy highlighted text to clipboard automatically 

### ISSUE THREAD

**Issue by sylank** [martyr-deepin/deepin-terminal-gtk#89]
As a developer, I want to copy the selected text to the clipboard automatically in selection time.

**Comment by wangjia12** [comment]
I'm afraid this feature is not in our plan at the moment.

**Comment by BLumia** [comment]
FYI you can directly paste selected text to terminal by middle clicking :)

**Comment by sylank** [comment]
Thank you for the information :) it is helpful.

Basically, this is not a new feature. I just created a new checkbox to set the config property. I realized, somebody developed this feature before me. I think it could be helpful to use a checkbox to turn on/off this property.

**Comment by BLumia** [comment]
After discussion with product manager @wangjia12 , we can accept this PR, kinda busy now, will review and test your PR later :)

-------------

@zhuxiujuancindy 考虑一下文案？目前提供的是 "Copy on select" ，意图是 “选择文字时自动复制内容到剪切板”。

**Comment by zhuxiujuancindy** [comment]
英文： Copy on select
@wangjia12 请确定中文文案

**Comment by wangjia12** [comment]
【选中文字时自动复制到剪切板】
