### ISSUE TITLE
在ubuntu17.04上无法使用远程管理功能

### ISSUE THREAD

**Issue by onhao** [martyr-deepin/deepin-terminal-gtk#9]
报错如下
expect -f /tmp/deepin-terminal-NZ25ZY
spawn zssh -X -o ServerAliveInterval=60 root@wuhao.pw -p 22 -o PubkeyAuthentication=no -t echo 欢迎使用深度终端， 在您使用右键菜单进行上传和下载文件之前， 请先确保服务器已经安装了rz和sz命令。 && exec $SHELL -l
out of pty's

**Comment by manateelazycat** [comment]
你需要手动安装 zzsh/lrzsz 这两个包，服务器也需要安装 lrzsz
