### ISSUE TITLE
使用zsh时无法识别当前目录

### ISSUE THREAD

**Issue by wangzk** [martyr-deepin/deepin-terminal-gtk#90]
如果当前的本地shell是zsh的时候，deepin-terminal在标签页上无法识别当前的目录，导致标签页没有名称。

具体情况见下图。

![image](https://user-images.githubusercontent.com/2674020/50389317-e2d0c400-0763-11e9-88c5-4a14880219e9.png)

**Comment by BLumia** [comment]
我这边使用 oh-my-zsh 的时候是正常的，你看看 `echo $PS1` 的输出？

**Comment by wangzk** [comment]
echo $PS1的结果是`%B%{%}%(4~|%-1~/.../%2~|%~)%u%b >%{%}>%B%(?.%{%}.%{%})>%{%}%b`。

估计和这里面包含太多环境变量有关？

**Comment by BLumia** [comment]
不清楚，回头我试一下看看能不能复现.. 我目前的 zsh 相关配置是[这个](https://github.com/BLumia/BLumiaGist/blob/master/.dotfiles/oh_my_zsh/custom/bashy.zsh-theme)

PS. 感兴趣的话，可以看看：

https://github.com/linuxdeepin/deepin-terminal/blob/ffd360847bb66f443ebc2b9bc4a738109e9280a7/widget/terminal.vala#L758-L803

 ，以及如果有兴趣自己构建的话，建议把 Vendor lib 关掉（cmake 的时候 `-DUSE_VENDOR_LIB=OFF`）

**Comment by zhaoyunxing92** [comment]
这个问题解决了吗，我的也oh-my-zsh也识别不到当前目录

**Comment by zhaoyunxing92** [comment]
我的echo $PS1  `${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)`

**Comment by BLumia** [comment]
没有抽出时间处理，如果有兴趣的话建议按上面给出的相关源码看看原因是啥 - -||

**Comment by xausky** [comment]
调试半天发现不是 deepin-terminal 的锅，以下配置加到 .zshrc 就好了。
```
case $TERM in
  xterm*)
    precmd () {print -Pn "\e]0;%n@%m:%~\a"}
    ;;
esac
```
不过 deepin-terminal 的标题获取逻辑还是有问题，`vte_window_title` 获取不到应该显示 "终端" ( 仿照 gnome-terminal ) 或者 _("deepin") 而不是现在的全黑了。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
