### ISSUE TITLE
Can't change transparency in Deepin 15.8

### ISSUE THREAD

**Issue by guacamolazo** [martyr-deepin/deepin-terminal-gtk#94]
After executing upgrade in terminal and reboot I am unable to change transparency in dock from control center in deepin. Despite I modify the value trough personalization, it doesn't change at all, it remains with a full transparency which difficults to read options in control center or even the hour when a white window is displayed on desktop. I created another account but the issue persists

**Comment by hualet** [comment]
Oh, that is so misleading...deepin terminal has separate transparency control against control center, dock, etc. There's transparency setting entry in its' own settings.

**Comment by horvan** [comment]
Maybe you are using Virtualbox and therefore some problems with terminals transparency appearing 

This post is just for the record.


After some testing, I found out that Deepins transparency feature at least with Virtual box 6.0 just works by using the following settings
## Display:
### VMSVGA
### 3D acceleration on
### 128 MB ram 

So this is not a bug in deep in it is just a configuration thing

**Comment by BLumia** [comment]
Thanks for the info!

Closing :)
