### ISSUE TITLE
Solarized color problems

### ISSUE THREAD

**Issue by egmontkob** [martyr-deepin/deepin-terminal-gtk#96]
In `theme/solarized light`, the value of `color_16` doesn't match the specification, under the section "The Values" on the [Solarized homepage](https://ethanschoonover.com/solarized/). This is clearly a bug. (It's defined correctly in `theme/solarized dark`, though.)

The `foreground` values in both files are also heavily debatable. Strictly speaking, the Solarized specification isn't aware of the concept of the terminal's "default" background and foreground colors. However, just as you did with the background, all terminal emulators that implement these color schemes decided to go with the "body text / default code / primary content" color, as shown under the "Usage & Development" section. In my opinion this makes much more sense than coming up with a custom one (the custom choice is presumably not backed up by similarly careful work as the author's with color distances and such, and also if every terminal did so then they'd all pick a different color which is against the goal).

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
