### ISSUE TITLE
Remove UTF-16

### ISSUE THREAD

**Issue by egmontkob** [martyr-deepin/deepin-terminal-gtk#97]
After opening the Encoding menu, the second choice offered is UTF-16.

Due to the nature of terminal emulation, only ASCII compatible encodings are usable. See e.g. https://bugs.kde.org/show_bug.cgi?id=395171.

Non ASCII compatible encodings shouldn't be offered.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
