### ISSUE TITLE
-e 只能运行文件不能执行语句? 

### ISSUE THREAD

**Issue by CareF** [martyr-deepin/deepin-terminal-gtk#98]
希望从命令行启动终端并执行特定命令 (比如我在写一个 app, 用户点击某个按键的时候, 打开终端并且在终端中执行指定的指令). 在 gnome-terminal 下可以如下执行: 

```
gnome-terminal -e 'sh -c "echo hello; read"'
```

deepin-terminal 也有 -e 的启动选项, 但同样的命令会提示: 

> terminal.vala:1246: Terminal launch_idle_id: Failed to execute child process “sh -c "echo hello; read"” (No such file or directory)

看起来 -e 之后的参数只能是一个文件名而不能是一条指令. -x 似乎和 -e 是一样的. 
不知道是没有实现这个功能还是我没有正确的使用它?

**Comment by BLumia** [comment]
看了一下，应该是没有实现这个功能。

**Comment by CareF** [comment]
发现把单引号去掉就行了 (捂脸)

```
deepin-terminal -e echo hello &
```

两处不同: 
1. 不需要手动加 read 看运行结果, deepin-terminal 默认要按键再退出
2. gonme-terminal 是自动在后台, 不会阻塞当前命令行, deepin-terminal 则会. 所以要加 & 扔到后台运行.
