### ISSUE TITLE
Deepin terminal in Arch shows annoying username@hostname in every opened tab

### ISSUE THREAD

**Issue by elswerky** [martyr-deepin/deepin-terminal-gtk#99]
I noticed an annoying feature (don't want to say it bug ))  in deepin terminal in arch and arch based distro as manjaro ,,, where it shows in the name of every opened tab 
**_username@hostname-path_**  in every opened tab name  which is very annoying to get a long name for the tab ,,,, i know i can rename tab by F2 ,,,

but in deepin os itself ,,this annoying thing isn't present in deepin terminal in deepin os  

like in this screenshot from manjaro deepin 
![deepinscreenshot_select-area_20181231165158](https://user-images.githubusercontent.com/26687459/50560749-93af0400-0d0c-11e9-83ed-ee579194a886.png)

![deepinscreenshot_select-area_20181231173445](https://user-images.githubusercontent.com/26687459/50561394-e55a8d00-0d12-11e9-9fb8-6ca6d5e824ab.png)

**_but here in v2.9 wasn't presnet_**

![trminal](https://user-images.githubusercontent.com/26687459/50562022-1b027480-0d19-11e9-93ca-64514a20959b.jpg)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
